### ISSUE TITLE
Webinterface negative graph not in view

### ISSUE THREAD

**Issue by milefork** [volkszaehler/volkszaehler.org#185]
Hi,

it's me again as you can see in the image:
![image](https://cloud.githubusercontent.com/assets/1383479/4559236/e6c58c58-4ee9-11e4-9e9c-191b22218a39.png) the negative Graph is out of the Diagram and it won't come in even if I zoom out and so on.
The Diagram will be every time positive.

Greetings

**Comment by rhartmannh** [comment]
The code to comment out is no longer in the source file. Obviously something has been changed. However, the error still exists. Is there another workaround?

**Comment by dervitti** [comment]
@rhartmannh I have (had) the same problem. You have to edit your /www/volkszaehler.org/htdocs/frontend/javascripts/entity.js to comment the lines. It´s in the part "Set axis minimum depending on data".

**Comment by rhartmannh** [comment]
Thanks. That helped.

**Comment by andig** [comment]
@all: can you confirm that this problem only exists when channels with negative and non-negative values are mapped to the same axis?

**Comment by milefork** [comment]
yes, i can confirm that.
