### ISSUE TITLE
Feature request: Date range selector in Frontend

### ISSUE THREAD

**Issue by nyphis** [volkszaehler/volkszaehler.org#210]
I would like to see a more advanced way to select the time range shown in the graph.

In my eyes the date range shown as heading could be a little more "interactive". 
If you click a date (start date or end date) a date selector div (calendar) shows up to enter the exact date range to be shown. 

I've seen something like this in Google Analytics (see attachment) and really liked it.
This would make things easier to select a complete day or month e.g. to get the overall cost of my heat pump.

![image](https://cloud.githubusercontent.com/assets/3128435/5604110/a572ef86-93a7-11e4-841e-f6bca28762ee.jpg)

**Comment by andig** [comment]
If interested start here http://jqueryui.com/datepicker/#date-range

**Comment by andig** [comment]
@nyphis which app did you take the screenshot from?

**Comment by nyphis** [comment]
Google Analytics
-----Original Message-----

**Comment by andig** [comment]
Tipp: um auf Tag/Monat/Jahr zu zoomen einfach einmal dafür sorgen dass das Chart den aktuellen Zeitpunkt nicht umfasst- dann werden jeweils komplette Intervalle selektiert.
