### ISSUE TITLE
extend entity type metadata (more than just name)?

### ISSUE THREAD

**Issue by r00t-** [volkszaehler/volkszaehler.org#212]
currently the entity (channel) -type definitions store only a single description string.
that is not really enough to differentiate the subtle differences between channel types
and at the same time be useful for frontend display.

i kind of opened this up, when i replaced the historic names:
http://volkszaehler.org/pipermail/volkszaehler-dev/2013-February/002397.html
http://volkszaehler.org/pipermail/volkszaehler-dev/2013-October/003121.html
https://github.com/volkszaehler/volkszaehler.org/commit/9486017571b7fe0d755bb5665a97e746ece3d70f

that created rather long names, which are not useful for the frontend display,
leading to stuff like:
https://github.com/volkszaehler/volkszaehler.org/commit/a8aabef209a30b98c7ec5baf5b5e06ed81a7ea86
https://github.com/volkszaehler/volkszaehler.org/commit/90eb44a21a46a23f641d0643e58e6bba599bcc51
and more recently:
https://github.com/volkszaehler/volkszaehler.org/pull/205

for a proper fix, we should support more than just a single name string.
useful would be:
- short display name (for frontend)
- long/detailed display name (for channel editor)
- description text ("help" text for clarifiation)

and, to make the conversions that happen more explicit:
- input data type/unit
- output data type/unit

**Comment by andig** [comment]
We should also add a unit description, e.g. "Leistung" for energy meters
