### ISSUE TITLE
composer install installs 23meg of jpgraph docs that no user needs

### ISSUE THREAD

**Issue by r00t-** [volkszaehler/volkszaehler.org#227]
root@raspberrypi:~# du -sch /srv/volkszaehler.org/vendor/jpgraph/jpgraph/lib/JpGraph/docs
23M     /srv/volkszaehler.org/vendor/jpgraph/jpgraph/lib/JpGraph/docs

that (plus probably the copies in .git) accounts for at last a third of the vz.org installation footprint...
does this really have to be installed from git, given that it's used so rarely?

**Comment by jahir** [comment]
Surely not. How can we prevent composer from installing it?

**Comment by andig** [comment]
Why is that a Problem? Every other package is installed from git, too?

Viele Grüße, Andreas

**Comment by andig** [comment]
Ups, I see. I'll create a fork and remove the docs.

**Comment by andig** [comment]
Opened issue with owner: https://github.com/ztec/JpGraph/issues/7

Meanwhile forged and updated jpgraph: https://github.com/volkszaehler/JpGraph/commits/master

Updated dependencies: https://github.com/volkszaehler/volkszaehler.org/pull/229

**Comment by r00t-** [comment]
let me try to clarify:
-  this is for a very rarely used feature, that most users don't know of and will never use
  (rendering graphs in the middleware instead of frontend)
- imho this neither justifies downloding many megabytes, nor a managing a fork
- does deleting files from git really reduce the download volume?
  matter of fact, it does not:
```
  $ git clone https://github.com/ztec/JpGraph JpGraph_ztec
  Receiving objects: 100% (2522/2522), 12.77 MiB | 2.94 MiB/s, done.
  $ git clone https://github.com/volkszaehler/JpGraph JpGraph_vz
  Receiving objects: 100% (2528/2528), 12.77 MiB | 4.47 MiB/s, done.  <---
  18M	JpGraph_vz
  46M	JpGraph_ztec
```

isn't there a composer target that just downloads a release tarball?
and even that could be made optional

also: from what i can tell, that ztec version isn't even the official one...?
what makes it better, why do we use it over the one from jpgraph.net?
(other than that composer prefers pulling stuff from VCSes?)

**Comment by andig** [comment]
> isn't there a composer target that just downloads a release tarball?

Nicht bekannt- und davon werden die Daten auch nicht weniger.

> also: from what i can tell, that ztec version isn't even the official one...?

es gibt kein aktuelles Composer Package da das Projekt tot ist.

> what makes it better, why do we use it over the one from jpgraph.net?

Weil es funktioniert.

Anders gesagt: Du kannst aus unserem JP Repo gerne alles rausschmeissen was Dich stört, ich weiss aber nicht was davon gebraucht wird...

**Comment by andig** [comment]
> 18M JpGraph_vz

Argh, natürlich- die Historie bleibt ja drin. Versuchs bitte nochmal, hab das Repo neu initialisiert.

**Comment by andig** [comment]
Wir könnten auch auf phantomjs umstellen. Das muss unter Windows aber von Hand installiert werden?

**Comment by jahir** [comment]
Äh, phantomjs ist doch ein kompletter Browser, nur headless. Größenmäßig werden wir dadurch wohl eher nichts gewinnen...

**Comment by andig** [comment]
Für Windows 8MB, aber stimmt. Dafür gibts dann die gleichen schicken Charts wie im Frontend.

**Comment by andig** [comment]
**ping**

wir könnens auch einfach sein lassen, aber wenn ich mir die Mühe schon mache wäre Feedback wirklich das Mindeste :/

**Comment by mbehr1** [comment]
+1

**Comment by r00t-** [comment]
i just noticed the problem and thought i'd report it.
i'm fine with any fix really.
so just merge https://github.com/volkszaehler/volkszaehler.org/pull/234 if you like

if you want my personal preference, then i'd make installing jpgraph optional and off by default. the feature is rarely used anyway.

**Comment by andig** [comment]
Closing as wfm.
