### ISSUE TITLE
Use Highstock to display graph

### ISSUE THREAD

**Issue by Xento** [volkszaehler/volkszaehler.org#238]
Is it possible, that you could switch to Highstock for displaying the graph?
http://www.highcharts.com/stock/demo
It supports touch devices, zooming, range selection and much more.

**Comment by adlerweb** [comment]
Commercial software - don't this this would be a good choice…

**Comment by Xento** [comment]
It is free for non commercial projects.

**Comment by adlerweb** [comment]
Volkszähler is not solely used in non-commercial environments so implementing it as a default could lead to involuntary license violations. Also the GPLv3 used here doesn't tolerate an NC-part so I don't think it would even be possible to create a bundle containing both codes.

**Comment by jahir** [comment]
One could code a new frontend with Highstock, but (as @adlerweb wrote) they would not probably not be allowed to re-use the current frontend code for it. Maybe there are ways to work around that (e.g. just have the API calls in the frontend code and let the user download Highstock separately), but I don't know if that's ok. Anyway, good luck with finding someone for the coding :)

**Comment by andig** [comment]
> It supports touch devices, zooming, range selection and much more.

@Xento: Apart from the licensing issues: what *exactly* are you missing with flot? As far as I understand we have touch support, zooming, we have range selection and we certainly have "much more".

Instead of describing the solution please start by explaining the feature you're missing.

PS.: Switching to highcharts would likely be 5~10 days effort exercise. If anybody wants this outside of the Volkszaehler core right now feel free to contact me.

**Comment by andig** [comment]
> Volkszähler is not solely used in non-commercial environments so implementing it as a default could lead to involuntary license violations. 

By the respective users. Would be their responsibility if we wanted to play it that way.

> Also the GPLv3 used here doesn't tolerate an NC-part so I don't think it would even be possible to create a bundle containing both codes.

What is NC? Indeed, the CC license of HighCharts (http://creativecommons.org/licenses/by-nc/3.0/) doesn't seem to be compatible with GPLv3 (https://wiki.creativecommons.org/Frequently_Asked_Questions).

**Comment by Xento** [comment]
Ok, here is what i'm missing. 
Mostly i use Volkszähler on my iphone. So i want to Zoom in and out with two Fingers and scroll through the Timeline with one Finger.

**Comment by andig** [comment]
> So i want to Zoom in and out with two Fingers 

There is a pinch plugin for flot, I'll need to take a look.

> and scroll through the Timeline with one Finger. 

Pan is supported as well.

See http://justindarc.github.io/flot.touch/

**Comment by Xento** [comment]
I added the touch plugin for flot, but it is very ugly.
It seems that you can only zoom the graph like an image. When you zoom with highstock it generates a new graph with the selected timespan.

**Comment by andig** [comment]
> I added the touch plugin for flot, but it is very ugly.

So? The plugin is 4 years old and needs a little work. That is what open source is about- build on what's there and start improving it.

**Comment by andig** [comment]
I've pushed an update to the plugins site. It now has what we need. All that's missing is the frontend integration to dynamically load the data.
