### ISSUE TITLE
Add touch support to the chart

### ISSUE THREAD

**Issue by andig** [volkszaehler/volkszaehler.org#239]
Follow-on of https://github.com/volkszaehler/volkszaehler.org/issues/238

**Comment by Saftwerk** [comment]
Vorschlag: Wenn ein Touch-Display kein Multi-Touch unterstützt, dann die obere Hälfte des Screens zum Zoomen verwenden und die untere Hälfte zum Scrollen.

Wischen nach rechts bedeutet dann ZOOMIN
Wischen nach links bedeutet dann ZOOMOUT

**Comment by andig** [comment]
replaced by #772
