### ISSUE TITLE
Falsche Berechnung des Verbrauchs

### ISSUE THREAD

**Issue by milefork** [volkszaehler/volkszaehler.org#268]
Hi,

ist es irgendwie möglich nur die positiven Werte auf den Verbrauch zu addieren? Also ich lese die 16.7.0 vom Stromzähler und mich würde es interessieren wie viel ich wirklich aus dem Netz gezogen habe. Aber bei der zusammen Rechnung des Verbrauches scheinen die negativen Werte auch aufaddiert zu werden. Hier mal ein paar Fotos:

http://puu.sh/gsnOC/337f25a1f2.png

Das nächste Bild kommt vom roten Bereich:

http://puu.sh/gsnTX/fd829fd2f1.png

Und mal eins wenn die Anlage Brummt, wobei man sieht das der Verbrauch definitiv im Minus ist, aber ich auch definitiv was aus dem Netz gezogen habe:

http://puu.sh/gso2Z/71fd2995fd.png

Kann mir jemand nen Tipp geben oder ist das nen Bug?

**Comment by andig** [comment]
Moin Christian,

Wenn ich Dich richtig verstehe möchtest Du den Teil der Kurve unter de x-Achse bei der Verbrauchsberechnung gerne ignorieren? Das ist leider nicht vorgesehen.

Viele Grüße, Andreas

**Comment by milefork** [comment]
Okay Danke für die schnelle Antwort!
Kann die middleware das irgendwie errechnen oder muss ich mir selbst nen Script schreiben?

**Comment by andig** [comment]
2015-03-09 15:54 GMT+01:00 Christian <notifications@github.com>:

> Okay Danke für die schnelle Antwort!
> Kann die middleware das irgendwie errechnen oder muss ich mir selbst nen
> Script schreiben?
>

Skript geht immer, Middleware leider nein. Hat Dein Zähler nicht evtl.
getrennte OBIS Codes für Einspeisung und Bezug die Du loggen kannst?

Viele Grüße,
Andreas

**Comment by jahir** [comment]
Hallo,

wie Andreas schon vorgeschlagen hat, solltest du möglichst einen anderen Kanal dafür benutzen. Den Momentanwert der Leistung zur Ermittlung der Energie zu benutzen ist theoretisch natürlich korrekt, aber wenn man das nicht sauber macht doch recht fehlerbehaftet.
Dein Zähler müßte doch auch Bezug und Einspeisung (als Zählerstand) getrennt ausgeben. damit bekommst du die genauen Zahlen und kannst auch den Eigenverbrauch berechnen.

**Comment by milefork** [comment]
Ja den habe ich natürlich auch. Aber ich glaube ich habe ihn falsch Konfiguriert, im Moment läuft er so:

http://puu.sh/gtQc4/c4ecb43da0.png

Kann es sein das ich ihn nicht als Leistungswert hätte konfigurieren sollen? Aber ich meine ich hatte diesen auch mal als Zählerstand, aber da habe ich die Auflösung nicht hinbekommen.

**Comment by andig** [comment]
Meist helfen vollständige Informationen statt rätselraten:

- was für ein Zähler?
- wie angeschlossen?
- welcher Kanaltyp?
- welcher OBIS Code"

Viele Grüße, Andreas

**Comment by jahir** [comment]
"Elektrische Energie (Leistungswerte)" ist Kanaltyp "power", das ist natürlich falsch.
Mit "electric meter" müßte die Anzeige dann stimmen. (Die Rumgezappel bei mir kommt von der schlechten Zählerauflösung und dem langsamen Auslesen.)
![volkszaehler org web frontend](https://cloud.githubusercontent.com/assets/508756/6571662/1d9425d4-c70b-11e4-9884-43655e8a8338.png)

**Comment by jahir** [comment]
Wobei mir gerade auffällt, daß die "574W" hier ja quatsch sind. Die Leistung liegt ab 17:55 bei ca. 7W (rechnerisch). Die 574W kommen vom nächsten Morgen, die zweite Zählerstandsänderung:

![volkszaehler org web frontend](https://cloud.githubusercontent.com/assets/508756/6571922/e3140e08-c70d-11e4-9952-5221ad39de11.png)

In den Werten sieht das dann so aus:

2015-03-09 16:58:16;1727.232;1
2015-03-09 17:02:11;1530.339;1
2015-03-09 17:07:33;1120.483;1
2015-03-09 17:19:18;510.646;1
2015-03-09 17:55:07;167.454;1
2015-03-10 07:36:13;7.307;1
2015-03-10 07:46:40;574.178;1

bzw.

2015-03-09 17:02:11;29030.5;1
2015-03-09 17:07:33;29030.6;1
2015-03-09 17:19:18;29030.7;1
2015-03-09 17:55:07;29030.8;1
2015-03-10 07:36:13;29030.9;1
2015-03-10 07:46:40;29031;1

Der letzte Wert sollte wohl eher nicht ausgegeben werden, der wird ja auch nicht mehr angezeigt. (Der vorletzte auch nicht, aber den brauchen wir halt, um einen "aktuellen" Wert anzuzeigen)
Naja, anderes Problem.

**Comment by milefork** [comment]
@andig also das hier ist mein Zähler: http://puu.sh/gupA2/c836ed2492.jpg 

Obis Codes die ich auslese:

1.8.0 Bezug Netz
2.8.0 Einspeisung Netz
16.7.0 Momentanleistung

**Comment by andig** [comment]
Ich steh auf dem Schlauch.

> Hab testweise mal die 1.8.0 auf electric meter gemapped 

Wieso? "1.8.0 Bezug Netz" dürfte eine Leistung sein, also Power.

> Also ich lese die 16.7.0 vom Stromzähler und mich würde es interessieren wie viel ich wirklich aus dem Netz gezogen habe.

Das wäre ja dann die "1.8.0 Bezug Netz", also einfach die richtig konfigurieren und es passt.

PS.: Das ist sicher kein Bug und gehört damit eigentlich auf die Mailingliste...

**Comment by milefork** [comment]
Okay weiß ich fürs nächste mal bescheid, wie erreiche ich die Mailing Liste?

**Comment by jahir** [comment]
1.8.0 ist ein Zählerstand ("Wirkarbeit Bezug")

**Comment by milefork** [comment]
@jahir also so erstellen? http://puu.sh/guthK/70cb405eb2.png

**Comment by andig** [comment]
Sollte passen. 

Viele Grüße,
Andreas

**Comment by milefork** [comment]
Okay muss das dann so aussehen? http://puu.sh/guxo2/52763213c6.png 
Jetzt muss ich nur noch die Auflösung anpassen oder?

**Comment by andig** [comment]
Ja, das sieht doch nicht schlecht aus. Du musst aber nicht jeden Schritt abnehmen lassen, einfach machen ;) Auflösung ist vmtl 1000 wenn Dein Zähler kWh ausgibt?

Viele Grüße, Andreas

**Comment by milefork** [comment]
Jo ist 1000 hab schon alles fertig, danke nochmal für eure Hilfe auch wenn's hier eigentlich nicht hingehörte ;)

**Comment by andig** [comment]
Immer gerne!
