### ISSUE TITLE
please explain more about the conf files

### ISSUE THREAD

**Issue by dave-watts** [volkszaehler/volkszaehler.org#276]
There is little documentation about the conf files, but they are quite important to operation. There are some nice howto's on your website relating to raspberry pi's etc but I don't see any explanation about how to create the conf file for a specific setup. For example, a common setup might be that you have a router and a smart meter (with a certain serial number) attached at an IP and port, what is a suitable conf file for connecting and reading from this meter, what are the specifics for different communication types (eg. SML, DMLS, IEC).

Thanks

Dave

**Comment by jahir** [comment]
I think you are talking about vzlogger config, the VZ middleware does not care what type of reader you use. Please reopen in the vzlogger repo.
