### ISSUE TITLE
volkszähler auf dem Webhoster installieren

### ISSUE THREAD

**Issue by cmeckler** [volkszaehler/volkszaehler.org#284]
Hallo,
ich hätte gerne eine einfachere und aktuellere Anleitung als die beiden welche ich im Netz gefunden habe.
http://wiki.volkszaehler.org/howto/installation_auf_webhoster

http://wiki.volkszaehler.org/howto/installation_auf_webhoster_2

am einfachsten währe ein komplettes Archiv mit dem Volkszähler drin.
in denen evtl die Pfadangabe durch PHP eigene Variablen gesetzt werden statt absolut, wie in der Anleitung beschieben.
Auch ein Troubelshooting währe hilfreich.

Vielen Dank an die tatkräftige Unterstüzung durch den Mailingliste
Gruß

**Comment by andig** [comment]
the second link gives working install instructions. First one deleted as incorrect.
