### ISSUE TITLE
Wrong composer.phar 

### ISSUE THREAD

**Issue by Spanni26** [volkszaehler/volkszaehler.org#287]
When calling "bash install.sh" it only checks if $COMPOSER is not empty. 

echo "checking composer..."
COMPOSER="$vz_dir/composer.phar"
if [ ! -n "$COMPOSER" ]; then
                for f in composer composer.phar; do
                               COMPOSER=$(which $f 2>/dev/null || true)
                                test -n "$COMPOSER" && break
                 done
fi

In my opinion it should be if [ ! -f "$COMPOSER" ]; then....so it checks for composer if $vz_dir/composer.phar is not found......

At the moment it fails cause there is no composer.phar in $vz_dir

**Comment by jahir** [comment]
Yes, the install script is broken in more than one way. I rewrote some parts of it (including the part you mention) but failed to open a pull request due to some usage git usage issues on my side. Will try to catch up asap.

**Comment by andig** [comment]
Should be fixed, please retest: https://github.com/volkszaehler/volkszaehler.org/commit/6ec5b312b9be305fb7d38551b2ecaced9e1651a3

**Comment by jahir** [comment]
reworked install script in https://github.com/volkszaehler/volkszaehler.org/pull/288

(btw, I merged your fix from master into development so I won't get merge errors. We should not let diverge the two branches too much...)

**Comment by andig** [comment]
@jahir right now dev is more for validating ideas- the commits on master are not identical. It should suffice to rebase dev on master from time to time.

**Comment by andig** [comment]
Fixes by #288
