### ISSUE TITLE
allow to select api grouping interval in the frontend by passing on the URL parameter from the frontend to the API

### ISSUE THREAD

**Issue by justinotherguy** [volkszaehler/volkszaehler.org#291]
Hi,
our API allows to select a grouping interval for the data retrieved from a channel. This way the upper limit for the resolution of the data can be set. E.g. if the data is present with a resolution of two seconds, the resolution can be lowered to one hour.
I've just checked, whether this features (I suppose, it's been rarely used) still works - and it does [2] :-)
Some URL parameters in the frontend (from, to, uuid) seem to be passed through to the API. For "group" this does not seem to be the case [3].
So here's my request:
the frontend should pass through the "group" parameter to the API to allow users to use this feature from the frontend.
What do you think?

Regards, J.

[1] http://wiki.volkszaehler.org/development/api/reference#daten-kontext
[2] http://demo.volkszaehler.org/middleware.php/data/12345678-1234-1234-1234-123456789012.json?from=1426833852183&to=1429425852183&group=day
[3] http://demo.volkszaehler.org/frontend/?from=1413583200000&to=1413669600000&uuid%5B%5D=12345678-1234-1234-1234-123456789012&group=day

**Comment by andig** [comment]
Will add. This takes away the resolution optimization of the frontend I've added for performance reasons but should be fine if explicitly requested.
