### ISSUE TITLE
/etc/volkszaehler.conf obsolete?

### ISSUE THREAD

**Issue by andig** [volkszaehler/volkszaehler.org#351]
From the README:

    volkszaehler.conf			this is a sample configuration for apache. Symlink it to /etc/apache2/conf.d/volkszaehler.conf

The file itself:

	# volkszaehler.org default Apache configuration

	Alias /volkszaehler.org /usr/share/volkszaehler.org/htdocs

	<Directory /usr/share/volkszaehler.org>
		Options AllowOverride FileInfo Limit Options Indexes
		DirectoryIndex index.php

		<IfModule mod_php5.c>
			AddType application/x-httpd-php .php

			php_flag magic_quotes_gpc Off
			php_flag track_vars On
			php_flag register_globals Off
			php_value include_path .
		</IfModule>

	</Directory>

  - seems to be compatible with Apache 2.2 only but not 2.4
  - is not used by the installer
  - magic quotes are obsolete anyway and not used
  - include_path is handled by composer

Suggesting to delete, including /etc/README.

**Comment by justinotherguy** [comment]
ACK!
