### ISSUE TITLE
Achsen Auflösung

### ISSUE THREAD

**Issue by milefork** [volkszaehler/volkszaehler.org#356]
Nabend,

so da unsere Solaranlage jetzt nicht mehr läuft fällt mir noch was auf. Die Skalierung der Achsen ist viel zu hoch. Hier mal ein Beispiel:

http://puu.sh/kuRAc/4add8d22df.png <- schön skaliert

http://puu.sh/kuRCe/ed6ca119d6.png <- ein Haufen Striche

Ich glaube es liegt an dem Peak den man im 2. Bild sieht dieser ist aber wenn man ihn sich näher anschaut nicht soooo groß, als das man noch das Doppelte darüber haben muss: 

http://puu.sh/kuRKX/80889637ea.png

Kann man das irgendwo einstellen?

Gruß

EDIT: Was auch interessant ist, dass wenn man die letzten beiden Bilder betrachtet die Linien ganz klar unterschiedliche Werte zeigen.

**Comment by andig** [comment]
Moin

> Am 01.10.2015 um 19:12 schrieb Christian <notifications@github.com>:
> 
> Nabend,
> 
> so da unsere Solaranlage jetzt nicht mehr läuft fällt mir noch was auf. Die Skalierung der Achsen ist viel zu hoch. Hier mal ein Beispiel:
> 
> http://puu.sh/kuRAc/4add8d22df.png <- schön skaliert
> 
> http://puu.sh/kuRCe/ed6ca119d6.png <- ein Haufen Striche
> 
> Ich glaube es liegt an dem Peak den man im 2. Bild
> 
Ja
> sieht dieser ist aber wenn man ihn sich näher anschaut nicht soooo groß, als das man noch das Doppelte darüber haben muss:
> 
> http://puu.sh/kuRKX/80889637ea.png
> 
> Kann man das irgendwo einstellen?
> 
Nein, das macht die Grafik selbst- oder gibts Skalierung fix vor (options.js).
