### ISSUE TITLE
Website: demo.volkszaehler.org should use "real" ssl certificate

### ISSUE THREAD

**Issue by andig** [volkszaehler/volkszaehler.org#370]
Any chance to move to http://letsencrypt.org?

**Comment by justinotherguy** [comment]
A good idea - major advantage from my perspective: more browsers than cacert.
Do you know, whether this can be used in fully manual "old fashioned CA mode"?
Whereas the fully default automatic mode is excellent for unexperienced admins, I don't really like the idea of having code run for this purpose.
I was unable to answer the question by checking letsencrypt's website.

**Comment by andig** [comment]
It is. I seem to recall a ct (or web?) article on the subject. It doesn't make sense though as the certs are shortlived (I believe 2 months currently). I'll check if I can find the source.

**Comment by schnello** [comment]
Hallo.

Also so schlecht ist "http://letsencrypt.org" im Grunde nicht. Die Zertifikate selbst halten zwar nur 3 Monate. Es gibt jedoch eine "auto update" Funktion. Wie gut oder schlecht die Arbeitet kann ich dann in 60 Tagen sagen.

Alternativ gibts dann noch https://www.startssl.com/
Sollte 1 Jahr sein... aber dafür braucht man Zugriff auf die postmaster EMail Adresse der Domain.


Grüße

**Comment by andig** [comment]
@justinotherguy implemented letsencrypt.
