### ISSUE TITLE
pushserver 'Uncaught TypeError: Cannot read property 'tuples' of undefined'

### ISSUE THREAD

**Issue by Sollner** [volkszaehler/volkszaehler.org#372]
Hallo,
bei aktiviertem Pushserver erscheint o.g. Fehlermeldung, wenn man bei mehreren abonnierten Kanälen einen oder mehrere Kanäle im frontend "abwählt".
sollner

**Comment by andig** [comment]
@Sollner / Patrick pls test

**Comment by Sollner** [comment]
test is ok ;-), thx
