### ISSUE TITLE
[live updates] table updated but not chart

### ISSUE THREAD

**Issue by andig** [volkszaehler/volkszaehler.org#381]
Reproducible @sollner11

**Comment by andig** [comment]
Additional issue: current period consumption not updated on live updates.

**Comment by andig** [comment]
cc @frankrichter for 2nd issue. First issue is wfm.

**Comment by frankrichter** [comment]
Genau, nicht aktualisierten Chart hatte ich noch nie, aber laufende Verbrauchsanzeige bei Push wär ne feine Sache.
Dann stellt sich noch die Frage: was machen mit min/max? Aktuell berechnen stell ich mir zu aufwändig vor, aber vielleicht wäre Darstellung in grau (für möglicherweise veraltete Werte) sinnvoll.

**Comment by frankrichter** [comment]
consumption update gibt es schon, ist nur nicht ganz richtig: https://github.com/volkszaehler/volkszaehler.org/blob/master/htdocs/js/entity.js#L224
wenn ich `this.consumption` zu `this.data.consumption` ändere, wird der Verbrauch brav aktualisiert.

Allerdings sollte die Berechnung von consumption eigentlich nicht von initialconsumption abhängig sein, und es fehlt eine Korrektur für die nach links aus dem Intervall rausgeschobenen Tupel.

**Comment by andig** [comment]
> es fehlt eine Korrektur für die nach links aus dem Intervall rausgeschobenen Tupel.

fehlt noch
