### ISSUE TITLE
Live updates: investigate if port 80 can be used instead of 8082

### ISSUE THREAD

**Issue by andig** [volkszaehler/volkszaehler.org#382]
This is possible. We need to add the following to `http.conf`:

	LoadModule proxy_module modules/mod_proxy.so
	LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so

	<Location "/ws">
	    ProxyPass ws://localhost:8082
	</Location>

If vhosts are used the `ProxyPass` need be added to both http and https section. Forwarding will always go to unencrypted `ws` port internally as `cboden/ratchet` does not support SSL (https://github.com/ratchetphp/Ratchet/issues/100).

As this approach doesn't need another port it would be the preferred solution. The `middleware.live` parameter would still be available if separate port is required.

This is also the only option to use `push-server` in an SSL setup.

Tested on Apache 2.4.

ping @justinotherguy could you add this config to demo.volkszaehler.org? Both locations would be required to allow http plus https.

**Comment by andig** [comment]
This is possible. We need to add the following to `http.conf`:

	LoadModule proxy_module modules/mod_proxy.so
	LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so

	<Location "/volkszaehler.org/ws">
	    ProxyPass ws://localhost:8082
	</Location>

	<Location "/volkszaehler.org/wss">
	    ProxyPass wss://localhost:8082
	</Location>

As this approach doesn't need another port it would be the preferred solution. The `middleware.live` parameter would still be available if separate port is required.

Tested on Apache 2.4.

ping @justinotherguy could you add this config to demo.volkszaehler.org? Both locations would be required to allow http plus https.

**Comment by justinotherguy** [comment]
ok, done - pls check, if this works - thx!
