### ISSUE TITLE
Messwertabfrage mit tuples=0

### ISSUE THREAD

**Issue by J-A-U** [volkszaehler/volkszaehler.org#383]
Laut Doku http://wiki.volkszaehler.org/development/api/reference#daten-kontext soll der Parameter &tuples=[Integer] die Anzahl an zurückgegebene Datenpunkten eingrenzen. Bei =0 sollen keine Punkte sondern nur die Ergnbnisse für die Tabelle im Frontend unten zurück kommen (min, max, consumption).
Dem ist aber nicht der Fall. Die Middleware antwortet mit allen Datenpunkten im angeforderten Zeitrahmen.

**Comment by andig** [comment]
Beispielaufruf? Gerne gegen demo damit es nachvollziehbar wird.

**Comment by J-A-U** [comment]
demo.volkszaehler.org/middleware.php/data/57acbef0-88a9-11e4-934f-6b0f9ecd95a8.json?from=7 days ago&tuples=0

**Comment by andig** [comment]
> http://demo.volkszaehler.org/middleware.php/data/57acbef0-88a9-11e4-934f-6b0f9ecd95a8.json?from=7 days ago&tuples=0

Erstmal sollten bei HTTP die ` ` eigentlich `+` sein, das geht aber meist trotzdem. Falsch ist `tuples=0`, mit `tuples=1` geht es. Schön wäre natürlich eine Fehlermeldung...

**Comment by J-A-U** [comment]
Im Wiki steht:
"für &tuples=0 werden nur Max, Min & Durchschnitts-Werte berechnet"
Ob das irgendwann mal so funktioniert hat kann ich aber nicht sagen.

OT: Die Leerzeichen sind ein C&P-Fehler. Normal macht Opera da ein %20 draus. In dem Fall seltsamerweise nicht.

**Comment by andig** [comment]
Du darfst das Wiki gerne korrigieren. 

Viele Grüße,
Andreas

**Comment by andig** [comment]
> Du darfst das Wiki gerne korrigieren.

Hat ja nix mehr mit dem Issue zu tun, ich machs also zu.
