### ISSUE TITLE
Virtuelle Kanäle

### ISSUE THREAD

**Issue by J-A-U** [volkszaehler/volkszaehler.org#384]
Einer von Andis Testzweigen hatte mal zusätzliche, virtuelle Kanäle die über eine Formel in den Kanalparameter aus anderen Kanälen errechnet wurden.

Bitte implementiert diese Funktion im Hauptzweig.

**Comment by andig** [comment]
Grosser Rewrite notwenig, momentan leider wenig Zeit. Kein "Issue"...

**Comment by J-A-U** [comment]
Verständlich. Ich dachte halt ich nehm mal den "offiziellen" Weg.

Was wäre denn die richtige "Art" um solcherlei Wünsche zu äußern?

**Comment by andig** [comment]
Der Meldeweg ist schon ok für Featurerequests. An der Zeit ändert das leider nix.

**Comment by mklhmnn** [comment]
Ja, gerade mit PV-Anlagen wäre es toll, z.B. den echten Hausverbrauch (PV-Erzeugt - Verkauft + Gekauft) anzeigen lassen zu können.

**Comment by andig** [comment]
Ich würde zusätzlich gerne noch eine Saldierung einbauen, also z.B um Tages- und Jahresproduktion aufzusummieren und als Kurve darzustellen. Leider ist das ein ziemlich aufwändiges Unterfangen...

**Comment by Saftwerk** [comment]
Ein "Virtueller Kanal" sollte gar keinen Platz in der Datenbank brauchen. Man kann die Werte vom Frontend aus den anderen abonnierten Werten berechnen lassen. Im Prinzip ist das dann wie eine Gruppe mit zusätzlicher Formel.

**Comment by andig** [comment]
Update: wer ganz mutig ist ohne keine Angst vor Schmerzen hat schaut mal hier rein: https://github.com/andig/volkszaehler.org da gibts auch virtuelle Kanäle in einer allerersten Testversion.

**Comment by TMHEINE** [comment]
Ist ja jetzt schon ne Weile her...
Gibt es inzwischen schon neueres oder Lösungsansätze?
Als PV-Besitzer wäre das wirklich super, um den Aktualverbrauch darzustellen (Erzeugung-Verkauf+Bezug=Aktualverbrauch)

**Comment by frankrichter** [comment]
Im verlinkten Fork von andig sind virtuelle Kanäle implementiert. Ich
benutze das seit über einem Jahr im Normalbetrieb. Einfach mal ausprobieren!

TMHEINE <notifications@github.com> schrieb am Fr., 29. Juni 2018, 09:09:
