### ISSUE TITLE
Neuen Kanaltyp "Wert (ohne Einheit)" einführen?

### ISSUE THREAD

**Issue by justinotherguy** [volkszaehler/volkszaehler.org#389]
Hi,
da das alles so prächtig funktioniert, verwende ich MW und FE inzwischen auch für ganz andere Dinge:
- verbleibende MB im gebuchten Traffic-Paket auf der SIM-Karte (Einheit: MB)
- Restguthaben auf dem SIM-Kartenkonto (Einheit: EUR)
- Anzahl Mitglieder auf einer ML
Da gibt es bestimmt weitere Anwendungsfälle. Für jeden Datentyp nun einen eigenen Kanaltyp zu definieren, erscheint mir nicht sinnvoll - einen zusätzlichen universellen Kanaltyp hingegen schon.
Der könnte dann entweder ganz ohne Einheit sein (die kann man dann ja im "title" eintragen) oder vielleicht sogar als Parameter die Eingabe einer Einheit erlauben.
Meinungen?
Gruß, K.

**Comment by andig** [comment]
Kein Problem, aber als was? Sensor, Zählerstand oder Impulse?

**Comment by justinotherguy** [comment]
Ich nutze bisher dafür "El. Energie (Leistungswerte)";
Ziel wäre, absolute Werte zu loggen; drum sind Impulse raus; 
Sensor dürfte auch nicht passen - Zählerstände, also, oder?

**Comment by andig** [comment]
> Ziel wäre, absolute Werte zu loggen; drum sind Impulse raus; Sensor dürfte auch nicht passen - Zählerstände, also, oder?

Ich denk Du bräuchtest Beides- Meter und Sensor. Muss das Ding "Verbäuche" können oder nur Graphen?

**Comment by KlausStetter** [comment]
Das hätte ich auch gerne!
Ich logge z.B. CO2-Konzentration in ppm, für die es schlicht nicht den richtigen Zählertyp gibt.
Ein universeller, am besten mit optional konfigurierbarer Einheit, wäre optimal.

**Comment by andig** [comment]
Moin,

Einen neuen Typ anzulegen dauert mit Texteditor 30 Sekunden- einfach selber einbauen? Gerne auch als PR zur Verfügung stellen. CO2 erscheint mir auch sinnvoll- deutlich mehr als "Radioaktivität" die wir schon haben...

Viele Grüße, Andreas

**Comment by KlausStetter** [comment]
Ok, hab das json-file gefunden, Danke.

**Comment by dervitti** [comment]
#411: Add Co2 and Fan rpm entity description and one new icon für co2

**Comment by andig** [comment]
VZ meeting: wird implementiert. Icon?

**Comment by andig** [comment]
@all Ich habe jetzt auch die Möglichkeit hinzu gefügt, für einen "universellen" Sensor eine Unit zu definieren.

** Könnte jemand den PR testen? **
