### ISSUE TITLE
Fehler unter Chrome bei 'export-Funktion'

### ISSUE THREAD

**Issue by UdoSchake** [volkszaehler/volkszaehler.org#393]
Wenn ich unter Chrome versuche die Daten als CSV zu exportieren bekomme ich folgende Fehlermeldung:
![export_fehler_chrome](https://cloud.githubusercontent.com/assets/6825833/12872047/57544aaa-cd96-11e5-8fb3-7eddbe2226be.PNG)

Unter FF funktioniert es:
![export_csv_ff](https://cloud.githubusercontent.com/assets/6825833/12872050/6e76c01e-cd96-11e5-9609-ca8a4d498ab9.PNG)

Gruß
Udo

**Comment by andig** [comment]
Gerade nachgetestet- geht bei mir, Chrome 48 auf Win 64. Aktuelles git?

**Comment by UdoSchake** [comment]
Jetzt aktuelles git.
Chrome 48 auf Win 64.
Cache und cookies gelöscht.
Fehler immer noch da.

Gruß
Udo

**Comment by andig** [comment]
Kannst Dus bitte mal mit dem Demo Link oben probieren? Danach hilft nur noch TeamViewer- muss ich live sehen.

**Comment by UdoSchake** [comment]
Also mit Chrome auf http://demo.volkszaehler.org/frontend funktioniert es.

**Comment by andig** [comment]
@UdoSchake ich machs zu da nicht reproduzierbar. Wenns wieder auftaucht bitte bei mir melden.
