### ISSUE TITLE
MS SQL Server Unterstützung

### ISSUE THREAD

**Issue by s4ndst0rm** [volkszaehler/volkszaehler.org#395]
Das Frontend nutzt bei der SQL Abfrage eine Funktion die es im SQL Server nicht gibt:

{"version":"0.3","exception":{"message":"An exception occurred while executing 'SELECT COUNT(DISTINCT YEAR(FROM_UNIXTIME(timestamp\/1000)), DAYOFYEAR(FROM_UNIXTIME(timestamp\/1000))) FROM data WHERE channel_id = ? AND timestamp >= ?' with params [1, 0]:\n\nSQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]'FROM_UNIXTIME' wird nicht als Name einer integrierten Funktion erkannt.","type":"DBALException","code":0}}

**Comment by andig** [comment]
Seems there is a number of sql functions missing- wontfix for time being.
