### ISSUE TITLE
Einheiten an den Achsen anzeigen

### ISSUE THREAD

**Issue by Rainer-Zufall** [volkszaehler/volkszaehler.org#396]
Bitte fügt an den Achsen die Einheiten an, wenn die Werte Ähnlich sind ist eine Unterscheidung der Achsen fast nicht möglich.

Stelle mir das so vor das einfach m³ oder KWH angefügt wird. 
![image](https://cloud.githubusercontent.com/assets/16509118/12919269/a11c02dc-cf43-11e5-9299-c0fb81336e14.png)

Danke!

**Comment by andig** [comment]
Wie wärs damit:

![unbenannt](https://cloud.githubusercontent.com/assets/184815/13009830/e5cdca8e-d19e-11e5-860e-5564658548fd.png)

Leider bekomme ich den Tick vor der Einheit nicht weg- sonst wärs eigentlich perfekt?!

**Comment by bgewehr** [comment]
Ich finde es richtig gut so!

**Comment by Rainer-Zufall** [comment]
Ja das sieht gut aus!
Evtl die Einheiten noch bis oben ziehen wie es früher war?

**Comment by andig** [comment]
Gibt die Chartlib leider nicht her. Den letzten "tick" könnte ich noch weghacken, mehr geht leider nicht. Wäre mal gut mit negativen Achsenwerten zu testen...

**Comment by Rainer-Zufall** [comment]
Dann bleibt es halt so. 👍
Mfg,
Am 12.02.2016 16:25 schrieb "andig" <notifications@github.com>:

**Comment by Sollner** [comment]
könnte man die Syntax in der options.js zu obigen Beispiel mal hier einstellen?
gerne auch erweitert um einen Max oder Min-Wert
Danke!

**Comment by andig** [comment]
Welche Sytax wofür?

**Comment by Sollner** [comment]
die entsprechenden Einträge für die Achsen in der options.js zu deinem obigen Beispiel

ps: 
deinen Ratschlag bezüglich Max-Wert bei Betriebsstundenzähler mag ich gerne umsetzen
nur was ist der Max-Wert wenn der Graph nur 0 und 1 annimmt
und der 1er-Wert dynamisch grafisch an meinen größten "anderen" Wert  angepasst wird
Danke.

**Comment by andig** [comment]
> die entsprechenden Einträge für die Achsen in der options.js zu deinem obigen Beispiel

Gar keine. Das ist ist Coding und muss noch hübsch gemacht werden.

> deinen Ratschlag bezüglich Max-Wert bei Betriebsstundenzähler mag ich gerne umsetzen

Gut- hat aber auch mit diesem Issue gar nicht zu tun. Wäre doch schön die Themen nicht immer durcheinander zu würfeln....

**Comment by Rainer-Zufall** [comment]
ist das jetzt schon implementiert?

**Comment by andig** [comment]
> ist das jetzt schon implementiert?

Soeben via https://github.com/volkszaehler/volkszaehler.org/pull/398 implementiert und bereit zum Test. Falls Fehler bitte dieses Issue wieder öffnen.
