### ISSUE TITLE
Code: Improve interpreter naming

### ISSUE THREAD

**Issue by andig** [volkszaehler/volkszaehler.org#415]
The current interpreters (https://github.com/volkszaehler/volkszaehler.org/tree/master/lib/Interpreter) naming is highly confusing. Need to check what they actually do every single time I need to change things:

  - Sensor reads current values (e.g. Leistung)
  - Meter counts impulses (e.g. S0) while a meter is really a "Zähler"
  - Counter does not count but takes actual meter readings in terms of "Zählerstände" (e.g. Verbrauch in kWh)

Suggestion to rename:

  - `SensorInterpreter` -> `SensorInterpreter` (as is)
  - `MeterInterpreter` -> `ImpulseInterpreter` (good description of what it does)
  - `CounterInterpreter` -> ~~`ReadingInterpreter` (doesn't make me entirely happy but seems to be the best translation around)~~ `AccumulatorInterpreter` (since the totals are accumulated over time)

In any case Sensor + Impulse are obvious and therefore make clear what Reading does. This is a potentially breaking change for anyone who has defined there own entity types.

Please comment.

**Comment by jahir** [comment]
I'm not fond of changing names, but IMO this is purely an internal change. Anybody using their own entity type is probably able to fix this by themself.
Go for it.

**Comment by andig** [comment]
Ideas: call the `CounterInterpreter` a `Sum(mator)Interpreter` or `MeterReadingInterpreter` (very similar to existing `MeterInterpreter`) or `DialInterpreter` or `CyclometerInterpreter` (Rollenzählwerk).

`AccumulatorInterpreter`?!
