### ISSUE TITLE
Frontend: ability to abort zoom-in triggered by click-drag-release

### ISSUE THREAD

**Issue by mklhmnn** [volkszaehler/volkszaehler.org#423]
- all click-drag-release events should be ignored if the time between click and release is less then, e.g. 1s
- click-drag should abort either on pressing ESC or when moving the mouse vertically outside the view

**Comment by andig** [comment]
Whats the use case? Is there an issue with the current behaviour?

**Comment by bgewehr** [comment]
Since drag and drop is used to build structured groups of channels this requirement should be rethought.

**Comment by mklhmnn** [comment]
The problem is that, especially with a touchpad, it is possible to trigger the click-drag-release by accident when trying to move the cursor. Undoing this zoom-in is not very easy to achieve.

**Comment by andig** [comment]
I'm confused. Zoom out is the minus button. What exactly are you trying to achieve?

**Comment by mklhmnn** [comment]
I want to prevent a) tiny drags (zoom into a very tiny time period - hard to undo with a lot of minus button presses and scrolling) and b) larger drags (on any operating system you can abort drag and drop operations by pressing ESC; it's for a good reason).

**Comment by andig** [comment]
Still unclear for me, sorry.
