### ISSUE TITLE
[live updates] Bereichsauswahl per Maus wird abgebrochen bei "Dateneingang"

### ISSUE THREAD

**Issue by schnello** [volkszaehler/volkszaehler.org#431]
Die Selektion per Maus über einen Bereich wird abgebrochen sobald im Frontend neue Daten dargestellt werden. Bei Livedaten aus dem pushserver (Intervall ca 1 Sekunde) ist somit eine Auswahl per Maus nur mehr schwer möglich.

**Comment by bgewehr** [comment]
Another isue, same reason: 
Each time i was hovering the chart with my mouse i got values shown in the legend.
Since i use the push server they get lost every second.
Can't we remember i was hovering and keep that state even if the chart moves on due to received push values?
If not, the hovering mode has become useless and we need another possibility to read values from a specific chart time. Maybe set a time mark which stays constant even if the chart moves on and display the values of that time mark in the legend?

**Comment by andig** [comment]
Leider steht Pushserver grad gaaaanz unten auf meiner Liste- erstmal muss ich nen Raspi3 beschaffen, dann neu installieren, dann vzlogger in Betrieb nehmen und mein Setup umziehen und dann kann ichs anschauen. Sorry...

**Comment by christian-weiss** [comment]
Bug ticket is more then 1 year old: Is this bug still existing?

**Comment by andig** [comment]
ping @schnello @frankrichter @bgewehr würdet ihr das mal testen?

**Comment by schnello** [comment]
Hallo.

Habs getestet und konnte leider keine Veränderung feststellen.


Grüße

**Comment by frankrichter** [comment]
Hier klappt es leider auch nicht.

Am 29. März 2018 um 10:53 schrieb andig <notifications@github.com>:

**Comment by frankrichter** [comment]
Update: ohne die Klammern hinter `vz.plot.getSelection` funktioniert's.

**Comment by andig** [comment]
> Update: ohne die Klammern hinter vz.plot.getSelection funktioniert's.

Schwer vorstellbar bzw. Zufall - dann wird nämlich gar keine Funktion aufgerufen. Ok, schaue ich nochmal an :/

**Comment by frankrichter** [comment]
War Unfug , sorry. Das blockiert Push-Updates generell...

**Comment by frankrichter** [comment]
Wenn ich die Erläuterung in volkszaehler.org/htdocs/vendor/flot/jquery.flot.selection.js richtig verstehe, wird getSelection erst nach erfolgreicher Selektion (Maustaste wieder losgelassen) ein Wert zugewiesen:

> getSelection()
> Returns the current selection in the same format as the "plotselected"
> event. If there's currently no selection, the function returns null.

Für unsere Zwecke könnte das hilfreich sein:

> A "plotselecting" event is fired during the process with the same
> parameters as the "plotselected" event, in case you want to know what's
> happening while it's happening

**Comment by andig** [comment]
Bitte nochmal schauen- die relevanten Teile sind eigentlich nur die paar Zeilen in `wui.js`. Bei mir lokal tut das. Problem war einfach dass der Redraw nicht passiert wenn die Daten kommen sondern erst nach Delay- und genau da wurde dann nicht mehr auf eine Selektion geprüft.

**Comment by andig** [comment]
@bgewehr separates Issue
