### ISSUE TITLE
Livedaten von einem Meter mit Zählerständen

### ISSUE THREAD

**Issue by schnello** [volkszaehler/volkszaehler.org#432]
Live Darstellung im Frontend von Daten eines Zählerstand-Meters ist "unschön" (siehe screenshot)

![1](https://cloud.githubusercontent.com/assets/6481341/15333537/570e117a-1c6a-11e6-969c-7d30514807ad.png)

**Comment by andig** [comment]
Ich habe PR https://github.com/volkszaehler/volkszaehler.org/pull/430 nochmal akualisiert. Bitte schau mal ob commit https://github.com/andig/volkszaehler.org/commit/c7d4c975b1c666290fac3823aa080cdb8989a21b das Problem löst.

**Comment by schnello** [comment]
Ist leider unverändert.

**Comment by andig** [comment]
Mhm. Zeigt Dir git log dass der Commit wirklich drin ist?

**Comment by schnello** [comment]
Ich bin jetzt nicht der git profi aber ich würde meinen ich hab alles richtig gemacht.

```
root@nas:/var/www/volkszaehler.org# git branch -v
  master 0a1363d [behind 4] Fix hhvm travis error
  test   44e0039 Merge commit 'refs/pull/430/head' of https://github.com/volkszaehler/volkszaehler.org into test
* test2  c7d4c97 Suppress duplicate counter values
```

Bzgl ssh:
Schick mir bitte per Mail deinen öffentlichen Key per Mail.

Grüße

**Comment by schnello** [comment]
Nachtrag:
Ich glaub ich hab den Fehler auf meiner Seite gefunden. Ich habe den Pushserver selbst nicht neugestartet. jedoch kann ich diesen nun gar nicht mehr starten:
`
Volkszaehler Push Server
Listening for updates on 5582. Clients may connect at 8082.
PHP Catchable fatal error:  Argument 1 passed to Volkszaehler\Server\MiddlewareAdapter::addAdapter() must be an instance of Volkszaehler\Server\PushClientMessageInterface, i
nstance of Volkszaehler\Server\WampClientAdapter given, called in /var/www/volkszaehler.org/misc/tools/push-server.php on line 97 and defined in /var/www/volkszaehler.org/li
b/Server/MiddlewareAdapter.php on line 62
root@nas:/home/nas# 
`

**Comment by andig** [comment]
Yep, habs gesehen und bin dran.

**Comment by andig** [comment]
@schnello versuchs nochmal

**Comment by schnello** [comment]
Sieht gut aus

**Comment by andig** [comment]
Closed via https://github.com/volkszaehler/volkszaehler.org/pull/430
