### ISSUE TITLE
Wunsch - min/max zulässige Werte pro Kanal

### ISSUE THREAD

**Issue by kr0815** [volkszaehler/volkszaehler.org#436]
Leider gibt es Sensoren die sporadisch falsche Werte senden, so z.B. meine Heizungssteuerung statt 53.8°C 128°C - das gibt dann unschöne Peaks im Diagramm

Man könnte das jetzt im sendenden Device unterbinden, leider ist das nicht immer einfach möglich.
(Ich setze kein VZLogger ein)

deshalb die Idee - man gibt pro Kanal optional min/max-Werte vor, alles darüber / darunter wird einfach ignoriert ?

**Comment by andig** [comment]
M.E. wäre das falsch. Die MW speichert und analysiert- für korrekte Eingangsdaten sind die Geräte/Controller verantwortlich. Wenn Du keinen vzlogger nutzt ohnehin leicht zu realisieren.

**Comment by andig** [comment]
@kr0815 Du kannst das mit wenig Aufwand aber im DataController selbst realisieren.
