### ISSUE TITLE
middleware: Javascript Runtime Error (reproduzierbar)

### ISSUE THREAD

**Issue by Saftwerk** [volkszaehler/volkszaehler.org#443]
Hergang:
Ich habe einen neuen Kanal vom Typ "Gruppe" erstellt und per Drag&Drop die Kanäle in die Gruppe verschoben. Leider werden nun immer alle Kanäle "aktiv" dargestellt. Ein "aktiv=off" lässt sich nicht  speichern. (das ist vielleicht ein anderes Issue)

Weil mir das "alles=aktiv" nicht gefällt, will ich die Kanäle wieder aus der Gruppe herausschieben - aber wie? Ich schiebe also das Blitz-Icon (Bolt) von einem Kanal auf die Zeile mit dem "Auge und Titel". Dann kommt der Fehler:

**Javascript Runtime Error
Uncaught TypeError: Cannot read property 'middleware' of undefined**

Und lustigerweise bleiben dort die Drag&Drop-Blitze alle liegen.

**Comment by andig** [comment]
Aktuelles git? Welcher Browser?
