### ISSUE TITLE
composer: "lock file is not up to date"

### ISSUE THREAD

**Issue by J-A-U** [volkszaehler/volkszaehler.org#447]
[Ein Nutzer](http://www.photovoltaikforum.com/volkszaehler-org-f131/wie-aktualisiere-ich-meine-middleware--t113237.html#p1399937) ist bei
`$ sudo composer install --no-dev`
über die Warnung gestolpert:
> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

Da muss wohl die composer.lock mal aktualisiert werden:
`$ composer update --lock`

**Comment by andig** [comment]
Die Antwort findet sich hier: http://stackoverflow.com/questions/33052195/what-are-the-differences-between-composer-update-and-composer-install

Für updates ist es daher besser composer update statt composer install zu nutzen, muss ggf im Wiki aktualisiert werden.

**Comment by J-A-U** [comment]
Wiki ändern - Check.

**Comment by andig** [comment]
Können wir das Issue dann wieder zu machen?
