### ISSUE TITLE
Total value is way too high

### ISSUE THREAD

**Issue by hundsmiachn** [volkszaehler/volkszaehler.org#448]
Hi

I'm having a small issue with the values at the bottom. When I select the year view it says a total usage of 1.1 MWh. All other views (month, day,..) show the correct value.

![unbenannt](https://cloud.githubusercontent.com/assets/11486047/16882950/e3e950f2-4ac1-11e6-8c8b-86185bf74129.jpg)

regards
Erich

**Comment by andig** [comment]
Hallo Erich,

Laut Screenshot ca. 800W x 24h x 2 Monate (60 Tage) sind ca. 1100kWh also 1,1 MWh. Wo siehst Du den Fehler?

Viele Grüße, Andreas

**Comment by hundsmiachn** [comment]
Hallo, sorry das stimmt natürlich. Ich hab mich da vertan. Mwh hat sich so viel angehört, aber es stimmt natürlich 
Sorry nochmals. 

Mfg
Erich

**Comment by andig** [comment]
Kein Problem- solte das für Strom mal in kWh ändern...
