### ISSUE TITLE
Middleware API Kanaldaten löschen

### ISSUE THREAD

**Issue by schnello** [volkszaehler/volkszaehler.org#449]
Aktuell kann über die Middleware API nur ein Kanal vollständig oder Daten gezielt mit dem Timestamp gelöscht werden. Die Option alle Kanaldaten bzw. in einem bestimmten Zeitfenster zu löschen fehlt und wäre eine sinnvolle Erweiterung der API.

**Comment by andig** [comment]
Gibts schon: https://github.com/volkszaehler/volkszaehler.org/blob/master/lib/Controller/DataController.php#L145
