### ISSUE TITLE
Push Server not starting

### ISSUE THREAD

**Issue by michelde** [volkszaehler/volkszaehler.org#455]
When trying to start the push-server.php an error occurs because the constructor of /lib/Controller/Controller.php was changed to have a new argument View: (start line 63)
`public function __construct(Request $request, EntityManager $em, View $view) {
$this->request = $request;
$this->em = $em;
$this->view = $view;
}
` 
The class lib/Server/MiddlewareAdapter.php which instantiates the controller is only passing 2 arguments: (start line 73)
`$this->controller = new EntityController(new Request(), $this->em);`

The whole error message when trying to start the push-server.php:

> PHP Catchable fatal error:  Argument 3 passed to Volkszaehler\Controller\Controller::__construct() must be an instance of Volkszaehler\View\View, none given, called in /var/www/html/volkszaehler.org/lib/Server/MiddlewareAdapter.php on line 73 and defined in /var/www/html/volkszaehler.org/lib/Controller/Controller.php on line 62

**Comment by andig** [comment]
Danke für den Hinweis. Habe ich mit 01f79b12292953d770bd032c7a99ada60295d592 mangels eines Testskriptes kaputt gemacht. Fix hoffentlich heute abend....
