### ISSUE TITLE
IE11: Javascript Runtime Error: Unbekannter Fehler

### ISSUE THREAD

**Issue by BlueAndi** [volkszaehler/volkszaehler.org#461]
Ich habe ein Update per git pull gemacht und ebenso den composer aktualisiert. Nun bekomme ich im Frontend einen Dialog mit dem 

> Javascript Runtime Error: Unbekannter Fehler

.
Frontend läuft auf einem Raspberry Pi, mit Raspbian wheezy. Das Betriebsssytem ist auf dem neuestem Stand.

Das Problem habe ich mit dem Firefox v48.0.2 nicht. Nur beim IE v11.
Cookies und Cache habe ich gelöscht, ohne Erfolg.

**Comment by J-A-U** [comment]
Aktiviere mal die Debug-Konsole:
Oben rechts aufs Zahnrad und "F12 Entwicklertools".

Als erstes wäre interessant ob im Reiter "Konsole" weiterführende Informationen zum Fehler zur Verfügung stehen.

**Comment by BlueAndi** [comment]
![fehler](https://cloud.githubusercontent.com/assets/9699465/18273535/fd5c1902-743d-11e6-8d9d-654f71435f39.jpg)
![fehler2](https://cloud.githubusercontent.com/assets/9699465/18273564/21305668-743e-11e6-90f0-68b9aaed720a.jpg)

**Comment by J-A-U** [comment]
Jupp, kann ich bestätigen. Allerdings macht der IE bei mir (bei abgestelltem Debug) trotzdem weiter und zeigt alles richtig an.

**Comment by BlueAndi** [comment]
Bei mir kommt immer dieser Dialog und wenn ich den mit "ok" bestätige, gehts auch weiter.
![fehlerdialog](https://cloud.githubusercontent.com/assets/9699465/18273659/aae78e62-743e-11e6-848e-fc9da4b88ea8.jpg)

**Comment by BlueAndi** [comment]
Ich habe mal kurz die aktuelle autobahn.js eingespielt. Der Fehler ist zwar weg, dafür kommt einer in init.js. Vermute da stimmen dann die Abhängigkeiten nicht mehr.

**Comment by BlueAndi** [comment]
Hier die Ausgabe der Konsole bei Firefox, vielleicht hilft das weiter:
![firefox](https://cloud.githubusercontent.com/assets/9699465/18280305/e7d00470-7458-11e6-9e3c-fd2b2c10d045.jpg)

**Comment by andig** [comment]
> Ich habe mal kurz die aktuelle autobahn.js eingespielt

Keine Ahnung was Du meinst. Die "aktuelle" ist bereits enthalten, also bitte rückgängig machen.

> Hier die Ausgabe der Konsole bei Firefox, vielleicht hilft das weiter:

Ich sehe da keinen Fehler. Anscheinend hast Du den Push Server nicht installiert, also alles wie erwartet. 

@BlueAndi Blöd ist der Fehler im IE. Kann ich mir das live anschauen? Url gerne per pm.

**Comment by andig** [comment]
Der Fehler ist behoben

**Comment by BlueAndi** [comment]
Wollte Dir gerade die URL freigeben. ;-)
Ich prüfe es gleich mal.

**Comment by BlueAndi** [comment]
Alles perfekt. Keine Fehlermeldung mehr im IE11. Firefox habe ich auch kurz geprüft, sieht gut aus.

Was noch kommt ist folgende Meldung in der Konsole:

> SCRIPT12008: WebSocket Error: Incorrect HTTP response. Status code 404, Not Found

Vermute aber das liegt dann wieder am nicht installierten Push Server.

Vielen Danke für den echt superschnellen Support!!!
