### ISSUE TITLE
weather script log_weather.sh is wrong

### ISSUE THREAD

**Issue by norbert-walter** [volkszaehler/volkszaehler.org#462]
The weather script _log_weather.sh_ in the folder _misc_ is wrong. The command _weather_ working not correct because the service from NOAA is out of service since 23.08.2016.

I changed the weather service from NOAA to OpenWeatherMap.org in the script. Now you need a application key for using the new script. You can order a free application key with a valid login by openweathermap.org.

I hope the service is longer available. Use the attached script, make executable and set the settings.
[log_weather.zip](https://github.com/volkszaehler/volkszaehler.org/files/456666/log_weather.zip)

**Comment by andig** [comment]
Fixed via https://github.com/volkszaehler/volkszaehler.org/pull/468
