### ISSUE TITLE
Add script for receiving high quality weather data

### ISSUE THREAD

**Issue by norbert-walter** [volkszaehler/volkszaehler.org#471]
Habe mal ein weiteres Script zu Wetterdaten unter miscs hinzugefügt, da ich gerade dabei war. Mit dem Script können high quality Wetterdaten bezogen werden, die von privaten Wetterstationen weltweit aufgezeichnet werden. Wenn man sich eine Station in seiner Nähe raussucht, dann können ortsgenau folgende Daten aufgezeichnet werden:

- Temperatur
- Taupunkt (interessant für Reifbildung und Glatteis, Photovoltaik)
- Luftdruck
- Luftfeuchtigkeit
- Solare Einstrahlung (interessant für Photovoltaik)
- UV Index

Der Dienst wird von WeatherUnderground bereitgestellt. Man benötigt einen Application-Key, den man nach kostenloser Anmeldung erhällt. Als Limit in der Free-Version kann man max. 500 Abfragen/Tag und/oder max. 10 Abfragen/min durchführen. Das sollte für ein 5min-Intervall ausreichen.

Hab ein Pull-Request dazu abgesetzt.

**Comment by andig** [comment]
Den Text hättest Du auch in den PR schreiben können ;)
