### ISSUE TITLE
Getting data is not supported for groups

### ISSUE THREAD

**Issue by BlueAndi** [volkszaehler/volkszaehler.org#476]
Did a fresh installation on a raspberry jessie and the current volkszaehler.org head.
After that I created a channel from the type building and a dialog "Getting data is not supported for groups" appears.

**Comment by J-A-U** [comment]
I can't recreate your problem, please give us some additional information.

For usual support please use our Mailinglist: http://wiki.volkszaehler.org/doku.php/contact
Und gerne auch in deutsch. ;)

**Comment by andig** [comment]
Introduced when refactoring- only happens when adding groups. Will fix asap.
