### ISSUE TITLE
Question - what hardware is also needed

### ISSUE THREAD

**Issue by TylonHH** [volkszaehler/volkszaehler.org#478]
Hi,
sorry for openening a issue for an individual question, but I dunno where else to ask.
I have here two eletric meter
**EasyMeter Q3DA1004 V3.04** for the house
**Elster AS1440** for my exhaust air heat pump with day / night / total counter

I also have one **Raspbbery Pi 3** wich I wanna to use. There is already an total different project running (https://github.com/pi-hole/pi-hole). Is that a problem?

What controller(?) do I need for those electric meter?

BTW: I'm german.

**Comment by andig** [comment]
Fragen bitte auf der Mailingliste stellen- danke!
