### ISSUE TITLE
Notiz / Kommentar an Grafen/Datensatz anfügen

### ISSUE THREAD

**Issue by TylonHH** [volkszaehler/volkszaehler.org#484]
Hallo,
was haltet Ihr von der Idee?
Man kann zu jedem Zähler zu jedem Zeitpunkt ein Kommentar hinzufügen. Im Idealfall direkt vom Frontend aus. So kann man sich Notitzen machen und diese später auch nachvollziehen.
Diese Datensätze sollten vom [Bereinigungsscript](https://github.com/volkszaehler/volkszaehler.org/blob/master/misc/tools/vzcompress2.php) ausgeschlossen aus.

**Comment by J-A-U** [comment]
Also so eine Art "Notizchannel"?
Wobei das keine Kleinigkeit ist. Unter data sind bislang nur Zahlen vorgesehen (Value ist vom Typ double).
Die andere Frage wäre wie der Text positioniert wird, kann jpgraph das selber machen oder müssen Textboxen immer "von außen" positioniert werden?

Nettes Feature wäre es, ich seh da durchaus auch einen Nutzen drin.
Persönlich find ich #442 und #384 aber bedeutender.
