### ISSUE TITLE
footer issue

### ISSUE THREAD

**Issue by schnello** [volkszaehler/volkszaehler.org#488]
Hallo.

Habe mit aktuellen Stand vom git das Problem das die Fußzeile nicht richtig skaliert (siehe Bild) wenn die Kanäle zugeklappt sind.
![image](https://cloud.githubusercontent.com/assets/6481341/19016065/ae0765c8-8810-11e6-985d-cdd198b76f1e.png)

Getestet mit Chrome, IE edge und Firefox

**Comment by andig** [comment]
Mit welchrn Schritten? Nur laden?

Viele Grüße,
Andreas

**Comment by schnello** [comment]
Einfach nur die Seite öffnen. Hier liegt leider das Problem jedoch scheinbar lokal bei mir:

> Also ich hab das jetzt nochmal getestet mit dem original stand bzgl der wui.js bzgl Line 45
> :   $('#entity-list').show(); // open entity list by default
> 
> Die hatte ich auskommentiert weil ich schon so viele Kanäle habe... damit die Kanalliste immer zu ist beim öffnen.
> Ist die Zeile aktiv, also die Kanalliste wird beim öffnen vollständig dargestellt, dann passt auch die Fußzeile. Also liegt das Problem leider schon auf meiner Seite indirekt. :(


Kann also geschlossen werden. Wenn es nötig ist bzgl der Darstellung die Kanäle zu laden dann muss es halt sein.

Grüße

**Comment by andig** [comment]
> Kann also geschlossen werden. 

:)
