### ISSUE TITLE
URL parameters for easy iframe integrations

### ISSUE THREAD

**Issue by bgewehr** [volkszaehler/volkszaehler.org#495]
Some special URL parameters like

http://<host>/frontend?channels={"UNID1","UNID2"}&chart=true&channeltable=false&footer=false&height=400px

would be a simple choice to put the volkszaehler frontend components into other web frontends by using an iframe.

The true or false values could result in display:none css styles for easy implementation.

A dynamic height would be perfect but as far as i know, flot is not able to be dynamic (100%) in height.

**Comment by andig** [comment]
Implemented via #498/#508.
