### ISSUE TITLE
hovering the chart with push server error

### ISSUE THREAD

**Issue by bgewehr** [volkszaehler/volkszaehler.org#496]
Each time i was hovering the chart with my mouse i got values shown in the legend of my chart.

Since i use the push server they get lost every second. 

Can't we remember i was hovering and keep that state even if the chart moves on due to received push values?

If not, the hovering mode has become useless and we need another possibility to read values from a specific chart time.

**Comment by andig** [comment]
Bitte hier mit ergänzen: https://github.com/volkszaehler/volkszaehler.org/issues/431 da gleiche Ursache.
