### ISSUE TITLE
Define and document Content-Security-Policy

### ISSUE THREAD

**Issue by ypid** [volkszaehler/volkszaehler.org#504]
Refer to: https://content-security-policy.com/

Could probably go into: http://wiki.volkszaehler.org/software/middleware/installation

**Comment by andig** [comment]
Add this to your `.htaccess`:

    Header set Content-Security-Policy "default-src 'self'; connect-src * ws: wss: http: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"

Won't add by default as it requires `mod_headers`.

**Comment by andig** [comment]
Please feel free to update the wiki.

**Comment by ypid** [comment]
Thanks!

Why not use:

```ApacheConf
<IfModule mod_headers.c>
    Header set Content-Security-Policy "default-src 'self'; connect-src * ws: wss: http: https:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
</IfModule>
```

?

No problem there with the `headers` module not being loaded.

**Comment by andig** [comment]
Nice. Care to file a PR?

**Comment by ypid** [comment]
Sure, done #509. Note that I currently have no instance running to test this with. I justed checked back because I wanted for a long time to set one up again and write a Ansible role to do the setup (would go into [debops-contrib](https://github.com/debops-contrib/)). Keep up the good work.
