### ISSUE TITLE
TypeError for newly created "Betriebsstundensensor" b/c of missing unit

### ISSUE THREAD

**Issue by justinotherguy** [volkszaehler/volkszaehler.org#514]
Moin,

I do this:
- open https://demo.volkszaehler.org/frontend/
- "Kanal hinzufügen"
- "Kanal erstellen":
  - "Betriebsstundensensor"
  - Titel "testtest"
  - Auflösung: 1
  - I leave all other entries at their default
  ->  "Erstellen"
  -> Popup with UUID (fd6a7600-ac95-11e6-9902-25dde84e7fbc)

Now , whenever I load the page or activate the channel I get an error message:
Firefox:
"TypeError: unit is undefined"

Safari:
"TypeError: undefined is not an object (evaluating 'unit.indexOf')"

Chrome:
"Uncaught TypeError: Cannot read property 'indexOf' of undefined"

Regards, J.

**Comment by andig** [comment]
Aktuelles git? Hast Du eine Unit angegeben?
