### ISSUE TITLE
favicon wird nicht angezeigt

### ISSUE THREAD

**Issue by bgewehr** [volkszaehler/volkszaehler.org#568]
das favicon wird nicht mehr angezeigt.

![image](https://cloud.githubusercontent.com/assets/4056277/22626465/32dc2936-ebae-11e6-9bd4-370242219168.png)

**Comment by andig** [comment]
Kann ich nicht nachvollziehen- bitte mal git pull und neu laden.

**Comment by andig** [comment]
Retested on demo, working.

**Comment by frankrichter** [comment]
Habe ich allerdings auch. Cache löschen und Apache Neustart bereits getestet. Pfade für die Icons sind ok, werden aber nicht gefunden.

**Comment by andig** [comment]
Na das is ja mal geil. Schauen wir ggf auch am Mittwoch an...

**Comment by BerndGewehr** [comment]
Ich bekomme auch auf dem iPhone kein Volkszähler Icon, sondern das Chart als Icon

**Comment by frankrichter** [comment]
Apache mag keinen Ordner namens `icons` im DocumentRoot, weil es dazu ein konfiguriertes Alias gibt:
[http://nixmash.com/php/solution-for-forbidden-icons-directory-in-apache/](http://nixmash.com/php/solution-for-forbidden-icons-directory-in-apache/)

**Comment by andig** [comment]
Also machen wir einfach /ico draus statt Apache Changes zu erfordern?

Viele Grüße, Andreas

**Comment by frankrichter** [comment]
Wird wohl das beste sein.
