### ISSUE TITLE
Option für Push-Updates in options.js

### ISSUE THREAD

**Issue by frankrichter** [volkszaehler/volkszaehler.org#575]
Könnte man in options.js eine Option zur einfachen Aktivierung/Deaktivierung von Push-Updates einbauen?

**Comment by andig** [comment]
Die gibts schon- für die MW einfach einen Port angeben auf dem keine Updates kommen.

**Comment by frankrichter** [comment]
Danke! Bei mir läuft die Variante mit Apache-Weiterleitung, deshalb wär ich nicht auf die Idee gekommen dass Aktivierung des auskommentierten Port-Eintrags was ändert. Aber wenn dadurch kein Verbindungsversuch zu ws://ip mehr erfolgt ist es klar.
