### ISSUE TITLE
Vzpushserver startet nicht

### ISSUE THREAD

**Issue by BerndGewehr** [volkszaehler/volkszaehler.org#580]
Fehlermeldung:
pi@volkszaehler:~ $ sudo /usr/bin/php /var/www/volkszaehler.org/misc/tools/push-server.php
Volkszaehler Push Server
Listening for updates on 5582. Clients may connect at 8082.
PHP Fatal error:  Call to undefined function GuzzleHttp\Psr7\parse_request() in /var/www/volkszaehler.org/vendor/react/http/src/RequestParser.php on line 98

**Comment by BerndGewehr** [comment]
War leider nur mobil, heute Abend gern formatiert, sorry!

**Comment by andig** [comment]
Fang bitte nochmal mit neuem git clone an und beschreib alle Schritte bis dahin. Wie gesagt- bei mir tut es!

**Comment by BerndGewehr** [comment]
- Verzeichnis komplett gelöscht
- install.sh neu ausgeführt
- neuer clone, composer läuft durch, setup beendet
- Zur Vorsicht apt-get update, apt-get upgrade
- Fehler beim Start des Pushservers:

```` 
root@volkszaehler:/var/www/volkszaehler.org# /usr/bin/php /var/www/volkszaehler.org/misc/tools/push-server.php
Volkszaehler Push Server
Listening for updates on 5582. Clients may connect at 8082.
PHP Fatal error:  Call to undefined function GuzzleHttp\Psr7\parse_request() in /var/www/volkszaehler.org/vendor/react/http/src/RequestParser.php on line 98
````

**Comment by andig** [comment]
Ok, also das passiert wenn sich der erste Client verbindet?

**Comment by bgewehr** [comment]
Habe mal composer update ausgeführt. 36 installs und 1 Update wurde ausgeführt. Nun läuft es.

Ich fange noch mal von vorn an und berichte.

**Comment by BerndGewehr** [comment]
Kennst Du den Moment, in dem einem auffällt, dass man sich schämen muss?

Ich habe mit einer älteren Kopie der install.sh im home-Verzeichnis gearbeitet. Mit der gab es die Fehler.

Neue install.sh geladen, keine Fehler. Habe mir die commit-history der install.sh angesehen und dafür keinen Grund erkannt, aber das scheint es gewesen zu sein. Tut mir leid!

**Comment by andig** [comment]
Hallo Bernd,

Ich hab Dich mehrfach gefragt ob Du wirklich aktuelles repo oder meinen PR verwendest.. jetzt ist die Antwort plötzlich ja.  

Ganz ehrlich: ich habe keine Zeit für Beschäftigungstherapie und bin nicht zu Deiner Bespassung da.

Ich verzichte ab jetzt draus Deine Probleme zu bearbeiten. Du musst Dir einen Anderen suchen- meine Zeit ist mir dafür zu kostbar.

Sorry,
Andreas

**Comment by frankrichter** [comment]
Ich hab vorhin auch mal einen neuen Clone angelegt und konnte den Push-Server ebenfalls nicht starten. Fehlermeldung wie bei Bernd:

`PHP Fatal error:  Call to undefined function GuzzleHttp\Psr7\parse_request() in /var/www/volkszaehler.org/vendor/react/http/src/RequestParser.php on line 98`

Vergleich mit älterem Clone ergab, dass im neu erstellten das Verzeichnis guzzlehttp/psr7/ unterhalb von vendor/ gar nicht existiert.

Hab dann noch ein bisschen rumgetestet und festgestellt, dass guzzlehttp/psr7/ wohl seit neuestem nur noch mit `composer install`, aber nicht mit `composer install --no-dev` installiert wird.
Da install.sh auch nur `--no-dev` installiert, sollte das behoben werden.

**Comment by bgewehr** [comment]
Das erklärt vielleicht auch, warum es mach composer Update plötzlich ging. Leider bin ich nicht so fit, um diese Zusammenhänge zu kapieren...

**Comment by frankrichter** [comment]
Denke ich auch. Die von dir genannten 36 installs/1 update sind genau die
Differenz zwischen require-dev und no-dev.
Am 19.02.2017 10:02 schrieb "Bernd Gewehr" <notifications@github.com>:

**Comment by andig** [comment]
Was sagt `git log`?

Bei mir:

````
commit 7cccaa90c55e8871dd7aa11172e16770d5255dd8
Author: andig <cpuidle@gmx.de>
Date:   Fri Feb 17 15:02:39 2017 +0100

    Workaround for react/http changes (#579)

**Comment by frankrichter** [comment]
Genau das.

2017-02-19 20:46 GMT+01:00 andig <notifications@github.com>:

**Comment by andig** [comment]
Ich kanns immer noch nicht reproduzieren, habe aber eine Idee. Bitte `composer update --no-dev` versuchen.

**Comment by frankrichter** [comment]
Hab eben nochmal neu angefangen, alles ok.
Den Stand ohne guzzlehttp kann ich gerade auch nicht reproduzieren. Keine Ahnung was ich da gestern gemacht hab. Könnte höchstens sein dass da eine composer.lock im Spiel war, die irgendwie Ärger gemacht hat.
Mea culpa für die Verwirrung, von mir aus schließen.

**Comment by bgewehr** [comment]
Ja, so ging es mir leider auch. Irgendwann ging es dann...

**Comment by bgewehr** [comment]
Heute geht es nach einem power-on Neustart übrigens wieder nicht:

````
pi@volkszaehler:~ $ /usr/bin/php /var/www/volkszaehler.org/misc/tools/push-server.php
Volkszaehler Push Server
Listening for updates on 5582. Clients may connect at 8082.
PHP Fatal error:  Call to undefined function GuzzleHttp\Psr7\parse_request() in /var/www/volkszaehler.org/vendor/react/http/src/RequestParser.php on line 98
````

**Comment by bgewehr** [comment]
install.sh vom frisch gezogenen repo geht auch nicht mehr:

````
pi@volkszaehler:/var/www/volkszaehler.org/misc/tools $ ./install.sh
volkszaehler.org installation script

checking prerequisites: php: /usr/bin/php
 mysql: /usr/bin/mysql
 awk: /usr/bin/awk
 sed: /bin/sed
 grep: /bin/grep
 wget: /usr/bin/wget
 mktemp: /bin/mktemp
 mkdir: /bin/mkdir
 git: /usr/bin/git

checking php version: 5.6.29-0+deb8u1 >= 5.6, ok

volkszaehler setup...
volkszaehler path? [/var/www/volkszaehler.org]
/var/www/volkszaehler.org already exists. Remove it and get new git clone? (you have to type 'Yes' to do this!) [n]

checking composer...
composer: /var/www/volkszaehler.org/composer.phar

installing dependencies...
/var/www/volkszaehler.org /var/www/volkszaehler.org/misc/tools
Loading composer repositories with package information          Reading composer.json of react/http (0.3)             Could not fetch https://api.github.com/repos/andig/http/contents/composer.json?ref=cf04457ef433cb128fd089b4b71abd4a6085bc7e, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+volkszaehler+2017-02-20+0745
to retrieve a token. It will be stored in "/home/pi/.composer/auth.json" for future use by Composer.
Token (hidden):
No token given, aborting.
You can also add it manually latReading composer.json of react/http (0.5)
Could not fetch https://api.github.com/repos/andig/http/contents/composer.json?ref=1fa41f84f183c14fb0c2fa005c911e501bd19fbb, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+volkszaehler+2017-02-20+0746
to retrieve a token. It will be stored in "/home/pi/.composer/auth.json" for future use by Composer.
````

**Comment by andig** [comment]
> install.sh vom frisch gezogenen repo geht auch nicht mehr:

Da auch das a) **überhaupt** nichts mit dem gemeldeten Fehler zu tun hat und b) die Fehlermeldung im Text ziemlich eindeutig ist aber gelesen und vielleicht gegoogelt werden will gehe ich davon aus dass das Ursprungsproblem gelöst ist.

**Comment by SirkoVZ** [comment]
ich hab auch Probleme mit dem ppm,
bei mir gibt es keine /var/www/volkszaehler.org/vendor/bin/ppm mehr
die composer.json enthält nicht mehr:

        "php-pm/php-pm": "dev-master",
        "php-pm/httpkernel-adapter": "dev-master"

(aber das(?):
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/andig/http"
        }
    ],
)

Hängt das damit zusammen?

ich hab gemacht
- sudo git pull
- composer.phar update

=> kein  /var/www/volkszaehler.org/vendor/bin/ppm mehr da

**Comment by SirkoVZ** [comment]
ok, beim 2. Versuch hab ich die ppm wieder, aber:
```
pi@raspberrypi /var/www/volkszaehler.org $ /usr/bin/php /var/www/volkszaehler.org/vendor/bin/ppm start -c /var/www/volkszaehler.org/etc/ppm.json
PHP Fatal error:  Class 'PHPPM\Commands\StartCommand' not found in /var/www/volkszaehler.org/vendor/php-pm/php-pm/bin/ppm on line 27
```

**Comment by andig** [comment]
> die composer.json enthält nicht mehr

@SirkoVZ was auch immer Du getan hast- die Installationsanleitung gilt weiterhin ;)

**Comment by SirkoVZ** [comment]
ok, nochmal von vorn:
- mein Stand von gestern (letztes git pull vom 3.2)
```
pi@raspberrypi /var/www/volkszaehler.org $ sudo git reset --hard origin/master
HEAD ist jetzt bei ee1023e added EntityDefinition filllevel (#578)
pi@raspberrypi /var/www/volkszaehler.org $ sudo git pull
Already up-to-date.
pi@raspberrypi /var/www/volkszaehler.org $ sudo ./composer.phar update
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information                                                                                                                                 Updating dependencies (including require-dev)           - Removing php-pm/httpkernel-adapter (dev-master)
  - Removing php-pm/php-pm (dev-master)
  - Removing mkraemer/react-pcntl (v2.0.0)
  - Removing symfony/process (v3.2.1)
  - Removing monolog/monolog (1.22.0)
  - Removing doctrine/collections (v1.3.0)
  - Installing doctrine/collections (v1.4.0)
    Loading from cache

  - Removing doctrine/common (v2.6.2)
  - Installing doctrine/common (v2.7.2)
    Loading from cache

  - Removing doctrine/dbal (v2.5.5)
  - Installing doctrine/dbal (v2.5.12)
    Loading from cache

  - Removing symfony/debug (v3.2.1)
  - Installing symfony/debug (v3.2.4)
    Loading from cache

  - Removing symfony/console (v3.2.1)
  - Installing symfony/console (v3.2.4)
    Loading from cache

  - Removing symfony/http-foundation (v3.2.1)
  - Installing symfony/http-foundation (v3.2.4)
    Loading from cache

  - Removing symfony/event-dispatcher (v3.2.1)
  - Installing symfony/event-dispatcher (v3.2.4)
    Loading from cache

  - Removing symfony/http-kernel (v3.2.1)
  - Installing symfony/http-kernel (v3.2.4)
    Loading from cache

  - Removing symfony/routing (v3.2.1)
  - Installing symfony/routing (v3.2.4)
    Loading from cache

  - Removing react/stream (v0.4.5)
  - Installing react/stream (v0.4.6)
    Loading from cache

  - Removing react/socket (v0.4.4)
  - Installing react/socket (v0.4.6)
    Loading from cache

  - Removing cboden/ratchet (v0.3.5)
  - Installing cboden/ratchet (v0.3.6)
    Loading from cache

  - Removing symfony/yaml (v3.2.1)
  - Installing symfony/yaml (v3.2.4)
    Loading from cache

  - Removing sebastian/object-enumerator (2.0.0)
  - Installing sebastian/object-enumerator (2.0.1)
    Loading from cache

  - Removing sebastian/comparator (1.2.2)
  - Installing sebastian/comparator (1.2.4)
    Loading from cache

  - Removing phpunit/php-code-coverage (4.0.4)
  - Installing phpunit/php-code-coverage (4.0.5)
    Loading from cache

  - Removing myclabs/deep-copy (1.5.5)
  - Installing myclabs/deep-copy (1.6.0)
    Loading from cache

  - Removing phpunit/phpunit (5.7.5)
  - Installing phpunit/phpunit (5.7.14)
    Loading from cache

  - Removing zendframework/zend-diactoros (1.3.8)
  - Installing zendframework/zend-diactoros (1.3.10)
    Loading from cache

  - Removing react/dns (v0.4.3)
  - Installing react/dns (v0.4.4)
    Loading from cache

  - Removing guzzlehttp/psr7 (1.3.1)
  - Installing guzzlehttp/psr7 (1.4.0)
    Loading from cache

  - Installing ringcentral/psr7 (1.2.1)
    Loading from cache

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Writing lock file
Generating autoload files

```

Danach ist tatsächlich der SymLink /var/www/volkszaehler.org/vendor/bin/ppm zu 
ppm -> ../php-pm/php-pm/bin/ppm
weg, ebenso wie /var/www/volkszaehler.org/vendor/php-pm komplett weg ist

siehe beim composer update oben:
 - Removing php-pm/php-pm (dev-master)

Das liegt wohl daran, daß im https://github.com/volkszaehler/volkszaehler.org/blob/master/composer.json
die zwei Zeilen weg sind?
        "php-pm/php-pm": "dev-master",
        "php-pm/httpkernel-adapter": "dev-master"

**Comment by SirkoVZ** [comment]
verdammt, ich bin im falschen issue, bei mir geht's gar nicht um den push server (der geht), sondern um den        php-pm

**Comment by andig** [comment]
Ich weiss ich nerve, aber:

@SirkoVZ (was auch immer Du getan hast) die Installationsanleitung gilt weiterhin. Ums deutlicher zu sagen: https://github.com/volkszaehler/volkszaehler.org/tree/master/misc/tools#installation

**Comment by SirkoVZ** [comment]
naaaagut ;-)
`composer require php-pm/php-pm:dev-master php-pm/httpkernel-adapter:dev-master`
war noch nötig.
Danke
