### ISSUE TITLE
Fehler bei unsubscribe in verschachtelten Gruppen

### ISSUE THREAD

**Issue by frankrichter** [volkszaehler/volkszaehler.org#588]
Setup: 
Gebäude/Gruppe/Kanal, push aktiv

Aktion:
Checkbox von Gebäude deaktivieren

Resultat:
Uncaught not subscribed to topic ...

vermutlich wird unsubscribe mehrfach versucht, ich konnte die Ursache aber nicht finden
wahrscheinlich kein Zusammenhang mit #586, da auch in next reproduzierbar

**Comment by andig** [comment]
Quick and dirty- einfach try/catch einbauen?

````
`Entity.prototype.unsubscribe = function() {
	var mw = vz.middleware.find(this.middleware);
	if (mw.session) {
		mw.session.unsubscribe(this.uuid);
	}
};

**Comment by frankrichter** [comment]
Von mir aus gerne.

Wahrscheinlich erschlägt das dann auch das eben entdeckte Problem, dass verschachtelte Gruppen nicht per Cookie auf inaktiv gesetzt werden können (Cookie wird nicht gespeichert, wahrscheinlich wegen dem vorher auftretenden Fehler). Ohne push klappt das nämlich.

**Comment by frankrichter** [comment]
Hab die Ursache gefunden, doppelte Rekursion in `activate`.
Und ja, die Cookie-Sache geht damit jetzt auch.
