### ISSUE TITLE
Failed to add Channel of type 'Sensor' with the unit 'g/m³'

### ISSUE THREAD

**Issue by nuccleon** [volkszaehler/volkszaehler.org#617]
Trying to add a channel for absolute humidity with the unit 'g/m³' caused the following exception:

> http://raspberrypi/volkszaehler/middleware.php/channel.json:
> Invalid property value: 'g/m³'

**Comment by andig** [comment]
How do you "add" a channel?

**Comment by nuccleon** [comment]
![2017-07-02-224618_1024x768_scrot](https://user-images.githubusercontent.com/24713434/27773363-4e032bae-5f78-11e7-864b-90ae2adc9def.png)

**Comment by andig** [comment]
Need to either add missing characters or open definition here https://github.com/volkszaehler/volkszaehler.org/blob/master/lib/Definition/PropertyDefinition.json#L449

**Comment by nuccleon** [comment]
Will you fix it?
