### ISSUE TITLE
Gruppen nach reload leer seit PR#626

### ISSUE THREAD

**Issue by J-A-U** [volkszaehler/volkszaehler.org#640]
Wenn man eine Gruppe (oder Gebäude) abonniert oder per URL aufruft ist diese erstmal wie gewohnt in der Tabelle des FE vorhanden und die untergeordneten Kanäle werden dargestellt (Tabelle und Graph).
Nach einem Reload der gesamten Seite taucht nur noch die Gruppe in der Tabelle auf, keine Kanäle und (wenn man keine einzelnen Kanäle abonniert hat) ein leerer Graph.

Ich konnte das Problem auf PR#626 (e2469cb) eingrenzen. Davor war das Verhalten nicht zu beobachten.

**Comment by jahir** [comment]
Kann ich bestätigen. Workaround: Details der Gruppe öffnen, Bearbeiten, Speichern.

**Comment by andig** [comment]
So, macbook repariert, getestet. Ich kanns nicht nachvollziehen. Gibt mir jemand HTTP/SSH Zugang zum testen? Habt ihr APCU installiert? Performance MW?

**Comment by BlueAndi** [comment]
Ich weiss nicht ob es das gleiche Problem ist, aber ich verwende das Debian Docker Image von Dir Andi.
Wenn ich wie folgt vorgehe, sind nach einem Browser Refresh alle in der Gruppe deaktiviert:
1. Gruppe deaktivieren (Ordner)
2. Einen in der Gruppe aktivieren
3. Browser refresh

Gehe ich anders vor, sind nach einem Browser Refresh all in der Gruppe aktiviert:
1. Gruppen aktivieren (Ordner)
2. Einen in der Gruppe deaktivieren
3. Browser refresh

Getestet via IE 11 und FF V56.0 mit jeweils gleichem Verhalten.

**Comment by andig** [comment]
> Ich weiss nicht ob es das gleiche Problem ist, aber ich verwende das Debian Docker Image von Dir Andi.

Das ist was Anderes. Die Gruppensichtbarkeit wird immer vom obersten Knoten bestimmt. Das ist das erwartete Verhalten bis wir eine coolere Lösung haben.

**Comment by J-A-U** [comment]
> Gibt mir jemand HTTP/SSH Zugang zum testen?

Erst am Wochenende, bin heute den ganzen Tag unterwegs.

> Habt ihr APCU installiert? Performance MW?

Apcu betrifft ja schon das PHP-Paket? Das ist drauf.
Ansonsten Standard-Installation per Script, keine PPM.

**Comment by andig** [comment]
Es gibt ein Cachingproblem. Workaround `devmode=true`, für eine richtige Lösung muss ich etwas Research machen, evtl. muss ich das zurück bauen :(

**Comment by andig** [comment]
Bitte mal testen- damit sollte es auch mit `devmode=false` wieder laufen.

**Comment by J-A-U** [comment]
Leider keine Besserung.

**Comment by andig** [comment]
Wtf. Zur Not Apache durchgestartet? Das *muss gehen* (tm). Darf ich da nochmal rein schauen?
