### ISSUE TITLE
Gefüllte Flächen im Diagramm

### ISSUE THREAD

**Issue by mode2k** [volkszaehler/volkszaehler.org#647]
Hallo,

 ich habe im Wiki folgenden Link gefunden
http://www.cd-k.de/2013/01/pimp-my-volkszahler-diagramm-gefullte-flachen-anzeigen/
der beschreiben soll wie man gefüllte Flächen im VZ hinterlegen kann (zB für Photovolatik). Leider ist der Link tot. Kann jemand beschreiben wie gefüllte Flächen möglich sind?

VG

**Comment by andig** [comment]
Füllgrad in den Kanaleigenschaften auf >0 setzen?

**Comment by mode2k** [comment]
OMG manchmal sieht man den Wald vor lauter Bäumen nicht. Funktioniert natürlich. Vielen Dank
