### ISSUE TITLE
(Temperatur-)Skalierung auf Y-Achse verliert Bezugspunkt

### ISSUE THREAD

**Issue by nuccleon** [volkszaehler/volkszaehler.org#652]
Aus der Mailingliste: [Temperatur Skalierung auf Y-Achse](https://marc.info/?l=volkszaehler-dev)

> Als Beispiel greife ich auf vergleichbare Graphen zurück die ich hier
habe. Raum- und Außentemperatur. Alle Kanäle außer die beiden sind
ausgeblendet. Aktuell gibts keine Minusgrade draußen, also bleibt die
Skalierung mit 0-25°C unverändert, auch wenn nur 1 Kanal dargestellt
wird.
>
>Gehe ich nun aber Tageweise zurück bis zu einer Stelle mit Minusgraden
wird neu skaliert. -5-25°C.
Lass ich jetzt nur einen der beiden Kanäle anzeigen verändert sich die
Skalierung. Bei Außentemperatur von -5-5°C. Bei Raum von 20-22°C.
Der Bezug auf 0° bleibt jetzt auch gebrochen wenn man in Zeiträume
zurückkehrt in denen nur Plusgrade im Graph auftauchen.
>
>Der Effekt tritt auch nur auf wenn die Skalierung nach unten
unterbrochen wird, wird wegen Überschreitung nach oben neu skaliert
bleibt der Bezug 0°C erhalten.

**Comment by andig** [comment]
Passiert das nur beim reinscrollen in einen entsprechenden +/- Bereich oder auch wenn schon initial entsprechende Werte existieren und nur Kanäle versteckt werden? Kann ich mir das evtl. in einer Installation (Link per PM) mal anschauen?

**Comment by nuccleon** [comment]
Passiert auch ohne scrollen. Aktivieren / deaktivieren eines Kanals reicht.
Link kommt per PM

**Comment by andig** [comment]
@nuccleon schau mal bitte ob das für Dich funktioniert. Sollte ziemlich vollständig sein solange Du nicht selber in den Options Axen angelegt hast- da gibts Sonderfälle die sich so nicht behandeln lassen. Das wäre dann aber ein anderes Thema....

**Comment by nuccleon** [comment]
> Javascript Runtime Error
> TypeError: axis is undefined

**Comment by andig** [comment]
Bäh! Ich sehe nicht in welcher Zeile das passieren soll? Zeilennummer? Magst Du Deine vollständige Datei mal posten? Bitte nochmal prüfen.

**Comment by andig** [comment]
Gibts neue Erkenntnisse? Sonst merge ich‘s so- dann findet der Nächste den Fehler 😬

**Comment by nuccleon** [comment]
Sorry, bin noch nicht dazu gekommen :-/Ich teste morgen Abend, versprochen...Am 18.03.2018 22:01 schrieb andig <notifications@github.com>:Gibts neue Erkenntnisse? Sonst merge ich‘s so- dann findet der Nächste den Fehler 😬

**Comment by andig** [comment]
> Ich könnte dir per PN mal nen link zu meiner Installation geben, dann kannst du dir das mal ankucken

Ja, mach mal bitte- HTTP reicht (cpuidle@gmx.de), dazu UUID vom Rootkanal um das anzuschauen.

**Comment by nuccleon** [comment]
Also der PR scheint okay.
Wenn er gemerged ist können wir das Issue zu machen.
