### ISSUE TITLE
DB Port konfigurieren

### ISSUE THREAD

**Issue by J-A-U** [volkszaehler/volkszaehler.org#666]
Die Middleware erlaubt derzeit keinen anderen als den Standard Port für die Datenbank. In der Konfig ist keine entsprechende Option vorgesehen.

Das führt zum Beispiel in Verbindung mit einem Wechsel von MariaDB5 auf MariaDB10 zu Problemen weil die neuere Version zusätzlich installiert wird und auf Port 3307 statt 3306 lauscht.

**Comment by andig** [comment]
> Die Middleware erlaubt derzeit keinen anderen als den Standard Port für die Datenbank. In der Konfig ist keine entsprechende Option vorgesehen.

Gib einfach einen `port` an?

**Comment by J-A-U** [comment]
Meinst du 
`$config['db']['host']				= '127.0.0.1:3307';`

oder
`$config['db']['port']				= '3307';`

**Comment by andig** [comment]
Entweder port separat oder gleich connect string angeben http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html

**Comment by J-A-U** [comment]
Ok.
Wäre es vielleicht angebracht den Parameter für Port in die Beispielkonfig mit einzubinden?

**Comment by andig** [comment]
Klar- wollen wir's so lassen oder gleich auf Connectstring ändern um die längliche Config gleich etwas auszudünnen? Evtl. mit dem Link zu doctrine? Magst Du einen PR machen?
