### ISSUE TITLE
Wunsch: Zoom bei mobile Seite bezogen auf Cursor Position

### ISSUE THREAD

**Issue by Feilner** [volkszaehler/volkszaehler.org#671]
Bei der Mobilen Webseite ist es nicht möchlich einen zoom-in mit der Maus zu machen.
Der Zoom-in und Zoom-out geschieht immer relativ zur mitte des dargestellten Bereiches.
Daher ist es nur sehr schwer möglich sich einen bestimmten Bereich zu vergrößern.

Wenn ein Cursor gesetzt ist solle der zoom-in und zoom-out so erfolgen, dass die Curserposition in der neuen Darstellung in der Mitte ist.

**Comment by andig** [comment]
Gute Idee!

**Comment by andig** [comment]
Closed via #771
