### ISSUE TITLE
Fehlermeldungen in vzlogger.log

### ISSUE THREAD

**Issue by TksHamburg** [volkszaehler/volkszaehler.org#672]
Moin,
ich sehe bei meiner neuen VZ-Instanz regelmäßig diese Fehler:

_[Mar 04 11:05:07][chn2] Middleware says duplicated value. Removing first entry!
[Mar 04 11:05:07][chn2] CURL Error from middleware: 'UniqueConstraintViolationException': 'An exception occurred while executing 'INSERT INTO data (channel_id, timestamp, value) VALUES (8,?,?), (8,?,?), (8,?,?), (8,?,?), (8,?,?), (8,?,?), (8,?,?), (8,?,?), (8,?,?), (8,?,?), (8,?,?), (8,?,?), (8,?,?), (8,?_

Muss mir das Sorgen machen?

VG
Christian

**Comment by andig** [comment]
Bitte auf der Mailingliste fragen- kein Fehler.
