### ISSUE TITLE
Allow query/delete data by value

### ISSUE THREAD

**Issue by andig** [volkszaehler/volkszaehler.org#676]
ich habe ab und an das Problem falscher Daten die ich gerne korrigieren bzw. löschen möchte. Schnell gemacht, aber nur per SQL- dazu muss ich auf den Server und bei Fehlern kann echter Schaden angerichtet werden.

Wie wäre es wenn wir das /data API- GET und DELETE- um einen value Parameter erweitern der folgende Möglichkeiten bietet (Quelle https://www.hl7.org/fhir/stu3/search.html):

    Searching on a simple numerical value in a resource. Examples:

    [parameter]=100    Values that equal 100, to 3 significant figures precision, so range [99.5 ... 100.5)
    [parameter]=100.00    Values that equal 100, to 5 significant figures precision, so range [99.995 ... 100.005). Whole numbers also equal 100.00, but not 100.01
    [parameter]=lt100    Values that are less than 100
    [parameter]=le100    Values that are less or equal to 100
    [parameter]=gt100    Values that are greater than 100
    [parameter]=ge100    Values that are greater or equal to 100
    [parameter]=ne100    Values that are not equal to 100

    Note: Uncertainty does not factor in evaluations. The precision of the numbers is considered arbitrarily high. (The way search parameters operate in resources is not the same as whether two numbers are equal to each other in a mathematical sense).

**Comment by andig** [comment]
Findet sich dafür ein Tester?

**Comment by frankrichter** [comment]
Hab ich vor, sobald ich etwas Zeit dafür finde.

andig <notifications@github.com> schrieb am So., 18. März 2018 22:02:
