### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by fis1497** [volkszaehler/volkszaehler.org#685]
Moin,
#683 
Commit cf63dce 

der letzte Commit verursacht bei mir einen Parse error ; PHP 7

PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in /var/www/volkszaehler.org/lib/Interpreter/Interpreter.php on line 112,

**Comment by andig** [comment]
Du bist Dir ganz sicher dass Du php7 verwendest? Da scheint zu funktionieren: https://3v4l.org/IYfLv

**Comment by fis1497** [comment]
Oh man, hast recht. der Apache war verbogen.
Alles wieder wunderbar.....sorry
