### ISSUE TITLE
Weather Underground out of API service at 31.12.2018 for weather data

### ISSUE THREAD

**Issue by norbert-walter** [volkszaehler/volkszaehler.org#708]
Hi,
Weather Underground stops the API service at 31.12.2018. For all users he use the API please change to the OpenWetherMap script log_weather.sh. After the date is the script log_weather_wu.sh not working.

@andig : Please remove the script from the repository. Thanks

Hare the received message:

"The WU API has been around since 2010 to help you develop apps and websites as well as manage your Personal Weather Station data. During that time, we’ve watched you build amazing products and visualize weather data with creativity and purpose.

Over the years, our infrastructure has been unable to keep up with the growing numbers of users coming to us for API data. This has led to higher costs as we worked to keep the service stable and dependable. Eventually, we realized we’d need to make drastic changes or risk serious problems for our API.

As a result, we’ve made the difficult decision to retire the Weather Underground API. The Weather Company, which acquired WU back in 2012, offers a powerful suite of enterprise-grade APIs that might be better suited to meet your scale and performance needs while offering a broader range of weather data. You can see these products here .

Here’s what you need to know going forward:

    Your subscriptions, and therefore access, will continue to work through 12/31/2018 .
    If you are a paying WU API customer , you will receive a call from a representative from The Weather Company, and IBM business, to discuss transition options to other API services. If you’d like to have these conversations sooner, contact us .
    If you are a Personal Weather Station owner , you will receive more information about our plan to offer free access to the data you provide to Weather Underground. We’ll reach out once that plan has been finalized.
    For developers who use WU API data for non-commercial purposes , you will have access to a new plan for a personal use, low call volume API. Stay tuned for more details as we build this out.
    The WU Forum will continue to be the best place to connect, keep you informed, share your feedback and get your questions answered as we go through this process.

We are grateful for your commitment to Weather Underground and appreciate your understanding and support as we work through this process. These changes will allow us to continually improve our services and develop new features to keep WU a thriving place for you for many years to come.

Thanks for being part of the community!
Sincerely,
The WU Team "

**Comment by andig** [comment]
ping @J-A-U can we remove the folder from this repo?
