### ISSUE TITLE
Kanaldialog: Beschreibung mit Zeilenumbrüchen anzeigen

### ISSUE THREAD

**Issue by thhoe** [volkszaehler/volkszaehler.org#713]
Ich hätte bei den Kanälen gerne ein Feld für zusätzliche Informationen, z.b. welche Verbraucher vom Zähler erfasst werden, oder Besonderheiten beim Standort von Sensoren. Das Feld soll im Frontend mit den anderen Eigenschaften angezeigt und bearbeitet werden.

**Comment by andig** [comment]
Es gibt schon ein Kommentarfeld, ist via middleware ausgeblendet. Kannst Du Dir aber wieder anzeigen.

**Comment by J-A-U** [comment]
Wo wird das an-/abgestellt. Ich hab gestern noch gesucht aber leider nicht wieder gefunden.

**Comment by frankrichter** [comment]
Müsste hiddenProperties in htdocs/js/options.js sein.

Am Mo., 26. Nov. 2018, 05:01 hat J-A-U <notifications@github.com>
geschrieben:

**Comment by thhoe** [comment]
Hallo,
> 
> Müsste hiddenProperties in htdocs/js/options.js sein. 
Genau das habe ich gesucht, vielen Dank.
Gibt es auch einen Trick einen Zeilenumbruch in diesen Feld?

**Comment by andig** [comment]
Im Browser? Ctrl/Alt/Shift Return?

**Comment by thhoe** [comment]
> Im Browser? 
Ja, Firefox 60.3.0esr (64-Bit)

> Ctrl/Alt/Shift Return?
Auch nicht. 

In phpmyadmin kann man den Text normal eingeben. In den Details für den Kanal erfolg die Anzeige aber einzeilig. Beim bearbeiten wird das Feld mehrzeilig angezeigt, eine neue Zeile konnte ich aber noch nicht einfügen.

**Comment by andig** [comment]
Hast Du mal Screenshot von Ein- und Ausgabe?

**Comment by thhoe** [comment]
![grafik](https://user-images.githubusercontent.com/45336831/49003058-73b28080-f161-11e8-80e9-00a9c016b435.png)
![grafik](https://user-images.githubusercontent.com/45336831/49003110-904eb880-f161-11e8-9fed-93cde6142765.png)

**Comment by andig** [comment]
Alles klar. D.h. für dieses Feld müssten wir speziell noch ein nl2br einbauen damit es sauber dargestellt wird.
