### ISSUE TITLE
please link to volkszaehler libsml

### ISSUE THREAD

**Issue by devZer0** [volkszaehler/volkszaehler.org#717]
https://wiki.volkszaehler.org/software/sml links to orphaned/old libsml in dailab repo in Section Software

please add link to maintained repo. this will help finding correct repo when doing google search for libsml

you may also like to add a link to https://www.npmjs.com/package/smartmeter-obis - this is a good sml parser, too

or maybe somebody could give me edit permission in volkszaehler wiki (user:rolandk), so i can fix that myself

**Comment by J-A-U** [comment]
> please add link to maintained repo. 

Check.

> maybe somebody could give me edit permission in volkszaehler wiki

Check.

**Comment by devZer0** [comment]
thanks!
