### ISSUE TITLE
push server is not enabled in docker image

### ISSUE THREAD

**Issue by bgewehr** [volkszaehler/volkszaehler.org#760]
Could you please explain the best way how to persistently enable push server on the docker image?

Please help a docker newbie...

**Comment by andig** [comment]
Please check if https://github.com/volkszaehler/volkszaehler.org/pull/761 works for you

**Comment by bgewehr** [comment]
Used the fresh image from volkszaehler/volkszaehler now.

Setup in config.yaml instead of php -> OK.
Error in frontend:

```
api/capabilities/definitions.json?unique=1556482801859:

Unknown context: 'api'
```

Google gives no hint on this one.

**Comment by bgewehr** [comment]
Docker container protocol tells:

```
8 workers (starting at 5501) up and ready. Application is ready at http://0.0.0.0:8080/ | stdout
Script did not return a valid HTTP response. Maybe it has called exit() prematurely? | stdout
```

**Comment by andig** [comment]
> Setup in config.yaml instead of php -> OK.

Please update image and retry (it's currently building and will hopefully publish).

**Comment by bgewehr** [comment]
Volkszaehler/volkszaehler docker image now runs without errors, but still without active push-server, correct?

Started push server manually 
`nohup push-server`

```
Volkszaehler Push Server                                                                                                       
Listening for updates on 5582. Clients may connect at 8082.  
```

Frontend seems to try to connect to push-server on port 8080 but fails
![image](https://user-images.githubusercontent.com/4056277/56877138-3887e680-6a4c-11e9-98f5-f04ecf6b2fff.png)

**Comment by bgewehr** [comment]
Changed options.js to enable live. Error is now gone, but I do not understand, why.

**Comment by bgewehr** [comment]
OK, it's not gone:
![image](https://user-images.githubusercontent.com/4056277/56877475-9c131380-6a4e-11e9-82f8-5bfe585d705a.png)

**Comment by bgewehr** [comment]
Container protocol sais:

```
Restart worker #5502 because it reached max requests of 1000 | stdout -- | --
Script did not return a valid HTTP response. Maybe it has called exit() prematurely? | stdout -- | --
```

**Comment by andig** [comment]
What is your setup? 

Do you realize that middleware and push server are two separate containers, i.e. are NOT sharing the same IP address?

Viele Grüße,
Andreas

**Comment by bgewehr** [comment]
I guess I did not yet understand how to set the tasks for a specific volkszaehler container. Is this done with an env variable? Can I create one with push-server only and another one with middleware and frontend? (and does that make sense to split? It would be still one service (=VZ) if pushserver would run inside of vz image, or do I get this wrong?)

(fyi: using docker on synology is a little bit less command line than typical docker is)

**Comment by andig** [comment]
Take a look at the included docker-compose. 
On Synology you can still use docker on the command line and I really recommend to do so or it will get very painful. 

Viele Grüße,
Andreas

**Comment by bgewehr** [comment]
OK, I now have two VZ-docker containers an I use the mariadb 5 from the synology services as my db.

![grafik](https://user-images.githubusercontent.com/4056277/56898026-5d9e4880-6a90-11e9-9810-0be799b775b9.png)

The push Server tells he's working
`Volkszaehler Push Server`
`Listening for updates on 5582. Clients may connect at 8082.`

And the frontend / middleware does work too.

BUT:
1) Updates are way slower than it was on the pi with local middleware, now far below once a second (does docker perform so much worse than a local middleware on the pi?)
2) Changed lines that come from other sources than push service (I use node-red too to send data to the middleware) will not update their lines in the chart until the complete page is reloaded or that channel gets hidden and shown by switching the checkbox in the channels list)

Is this the expected behaviour?

**Comment by bgewehr** [comment]
Well, sorry for the iterative self-responding, it shows my learning curve.

I guess 2) is why a push server actually exists and my node-red values do not trigger frontend updates without addressing the push server. I will try to send to the push service also from node-red.

**Comment by bgewehr** [comment]
This works now. Thanks for helping.
