### ISSUE TITLE
No Aggregation in docker image

### ISSUE THREAD

**Issue by bgewehr** [volkszaehler/volkszaehler.org#762]
In the current docker image there is no aggregation enabled.

What would be the best way to do it?

Place a script in /etc/periodic/hourly like

```
#!/bin/ash
php /vz/bin/aggregate run -m delta -l hour >/dev/null
```

or what is the best practice on docker?

**Comment by andig** [comment]
This is not possible in docker. Implement the cron job outside and have it execute in the running container using ˋdocker execˋ.
