### ISSUE TITLE
Frontend - Y - Achse 

### ISSUE THREAD

**Issue by 70sman** [volkszaehler/volkszaehler.org#764]
Bei der Anzeige des Luftdrucks ist eine Dardtellung der Y-Achse beginnend von 0 nicht unbedingt sinnvoll. Kleine Luftdruckänderungen kann man dann kaum erkennen.
Ähnliches Thema habe ich bei dem Gewicht meiner Bienen-Völker.

Vorschläge:
- Kanalbezogene (von UUID abhängige) Y-Achse  (Beim Anlegen oder Ändern des Kanals)
   Auswahl: min-Wert, auto-min.  , max-Wert , auto-max.
   wobei auto-x die Y-Achse automatisch vom min./ bzw. bis max. Wertes des Kanals (dargestellte  Zeitbereich )skaliert.

 Die aktuelle Frontend-Darstellung würde als somit 
 min-Wert = 0 , max-Wert = auto-max. entsprechen.

**Comment by jahir** [comment]
Siehe #727
