### ISSUE TITLE
how to add sonoff pow r2 with tasmota firmware as an energy meter

### ISSUE THREAD

**Issue by schlaubi666** [volkszaehler/volkszaehler.org#770]
I have an sonoff Stitch with buildin powermeter ( Sonoff POW R2) already flashed with tasmota firmware ( https://github.com/arendst/Sonoff-Tasmota/ )

If i login to the webgui i seen an Power output in W see picture

![1](https://user-images.githubusercontent.com/24993136/60759631-c1ad3200-a028-11e9-99bc-76a8c3c78087.jpg)

hot can i get this into volkszähler ?

**Comment by frankrichter** [comment]
Please use the mailing list to discuss user questions (gern auch deutsch).

Tasmota speaks MQTT and HTTP. Use Node-RED or the scrpting language of your choice to send the data to the volkszaehler API.
