### ISSUE TITLE
Graph wird nur mit Lücken angezeigt

### ISSUE THREAD

**Issue by p3ab0dy** [volkszaehler/volkszaehler.org#773]
Hi ich frage über ein Script einen Aquara Temperatur Sensor an. Neben der Temperatur erhalte ich auch einen Zeitstempel. Diesen rechne ich in ms um und schicken ihn an die API. Das Skript läuft alle 5 Minuten. Hat sich ein Wert nicht geändert würde das Skript versuchen diesen mit dem gleichen Zeitstempel einzutragen und die API würden diesen korrekt abweisen. 

Nun wollte ich vor kurzem ein Update auf die neue Version durchführen aber leider wird mir der Graph nicht mehr durchgehend angezeigt. 

Graph in alter Version:
`git describe --tags 0.7-34-g341bf0f `
![2019-07-31 14_29_04-volkszaehler org - web frontend](https://user-images.githubusercontent.com/11159624/62212399-ee8f0380-b3a0-11e9-87bc-b6418132e4f5.png)

`git describe --tags 1.0-54-g843fb56`
![2019-07-31 14_28_12-volkszaehler org - web frontend](https://user-images.githubusercontent.com/11159624/62212446-0bc3d200-b3a1-11e9-8b8e-350627eb945a.png)

Habt ihr eine Idee woran das liegen könnte? 
Ich habe die aktuelle Version im Moment parallel installiert und an die gleiche Datenbank angeschlossen. Also die Datenbasis ist bei beiden Instanzen identisch.

**Comment by frankrichter** [comment]
Schau mal in die options.js, da gibt's irgendwo eine Option "gap". Kannst
du auskommentieren oder die Zeit verlängern.

p3ab0dy <notifications@github.com> schrieb am Mi., 31. Juli 2019, 14:44:

**Comment by p3ab0dy** [comment]
Perfekt das war der Fehler!!! Vielen Dank!!!
