### ISSUE TITLE
Skalierung bei Stundendarstellung stimmt nicht

### ISSUE THREAD

**Issue by BoxSo** [volkszaehler/volkszaehler.org#780]
Wenn ich mir die Daten meines D0 (SML) Sensor am eZH darstellen lassen, scheinen die Werte initial zu stimmen. Die historischen Daten werden korrekt dargestellt. Die ab dem Zeitpunkt des Ladens der Seite gesammelten (nachgeladenen) Daten werden dann wohl durch 10 geteilt. 

Wenn ich dann wieder zwischen Tages- und Stundendarstellung wechsle, werden wieder bis zum Zeitpunkt des ladens der Seite alle Werte korrekt dargestellt. 

Es sieht so aus, als ob die Funktion, die die Daten kontinuierlich nachlädt, eine Division durch 10 durchführt. Auch der aktuelle Leistungswert unten in der Liste der Kanäle zeigt einen ggü. dem realen Verbraucht um den Faktor 10 geringeren Wert an (also z.B. statt 2.3 KW -> 230 Watt).

![Bildschirmfoto 2019-11-12 um 20 37 37](https://user-images.githubusercontent.com/3858285/68704546-bf398680-058c-11ea-8550-e1f1fd3e607c.png)
![Bildschirmfoto 2019-11-12 um 20 37 50](https://user-images.githubusercontent.com/3858285/68704547-bf398680-058c-11ea-8bc4-d0e49161fa47.png)

**Comment by andig** [comment]
Wie ist der Kanal konfiguriert?

**Comment by BoxSo** [comment]
Folgend die Konfiguration in der vzlogger.conf Datei
![Bildschirmfoto 2019-11-12 um 22 08 12](https://user-images.githubusercontent.com/3858285/68711032-0f1e4a80-0599-11ea-80f9-8b42259fecd0.png)
![Bildschirmfoto 2019-11-12 um 22 08 24](https://user-images.githubusercontent.com/3858285/68711033-0f1e4a80-0599-11ea-82ad-452cfc70981f.png)
Und hier die Einstellung des Channels:
![Bildschirmfoto 2019-11-12 um 22 08 40](https://user-images.githubusercontent.com/3858285/68711034-0f1e4a80-0599-11ea-845b-dfe944996e21.png)
Und das ist der zugehörige Zähler:
![Bildschirmfoto 2019-11-12 um 22 10 30](https://user-images.githubusercontent.com/3858285/68711235-89e76580-0599-11ea-8369-144788462fa7.png)

**Comment by frankrichter** [comment]
Hat deine vzlogger.conf wirklich keinen "push"-Eintrag?

**Comment by BoxSo** [comment]
oh doch ... hatte einen Screenshot übersehen beim hochladen:
![Bildschirmfoto 2019-11-12 um 22 39 10](https://user-images.githubusercontent.com/3858285/68713103-645c5b00-059d-11ea-8e57-86ea49dda4e5.png)

**Comment by frankrichter** [comment]
Ok, ansonsten wäre es etwas mysteriös gewesen, wo die beschriebenen
automatischen Updates herkommen. Die Konfiguration sieht für mich ok aus,
eine Erklärung für die falsch berechnete Leistung hab ich leider nicht
parat.

**Comment by J-A-U** [comment]
Erklärung hab ich auch nicht.
Da aber eh keine Aggregation genutzt wird würde ich den PUSH-Server mal deaktivieren um zu sehen ob das Problem weg geht. Wobei man den nicht nur im vzlogger abstellen kann, in der Middleware ist auch konfiguriert wo die Daten angenommen werden.

**Comment by frankrichter** [comment]
sudo systemctl stop push-server genügt, um kurz zu prüfen ob die falschen
Werte vom Push-Server kommen. Der Beschreibung nach gehe ich mal davon aus.
Längerfristig muss allerdings der Eintrag in der vzlogger.conf raus, sonst
läuft das Logfile voll.


J-A-U <notifications@github.com> schrieb am Mi., 13. Nov. 2019, 07:29:

**Comment by BoxSo** [comment]
Nach dem Beenden des push-server über sudo systemctl stop push-server stimmt die Anzeige des Charts und auch der Werte unterhalb des Chart. 

Ich nehme dann die push-Konfiguration aus der vzlogger.conf raus?
Hat das sonst irgendwelche Nebenwirkungen?

**Comment by frankrichter** [comment]
Du verlierst halt den Komfort, den der Push-Server bietet (laufende
Frontend-Updates an der Datenbank vorbei, näheres siehe Wiki).

Wenn der Push-Server falsche Leistungswerte berechnet, ist das ein Bug und
sollte näher untersucht werden - normalerweise sollte der mit der Auflösung
aus den Kanaleigenschaften arbeiten und korrekte Werte liefern.

>

**Comment by BoxSo** [comment]
Ich habe nun mittels sudo systemctl start push-server den Push-Service wieder gestartet und nun zeigt die Oberfläche korrekte Werte an (egal ob auf Stunden-Auflösung, Tag oder Woche). 

Ich hatte den Raspberry schon mehrfach neu gestartet zwischendrin.

Kann es sein, dass der push-server Änderungen am der Auflösung nicht automatisch mitbekommt?

**Comment by frankrichter** [comment]
Vielleicht ein Caching-Problem - gut dass es jetzt klappt! Dann solltest du
wie von J-A-U angedeutet vielleicht noch überlegen, ob du nicht die
Aggregation im vzlogger nutzen willst, aktuell sammelst du sehr viele
Datensätze, die die Speicherkarte stressen und wahrscheinlich nicht in der
Auflösung (1-3s) gebraucht werden.

Sorry für's OT: Was für einen Lesekopf hast du da im Einsatz? Ist der per
WLAN angebunden?

>

**Comment by J-A-U** [comment]
Das ist der Weidmann Lesekopf mit USB. Liegt bei ca. 45€.

**Comment by frankrichter** [comment]
Okay, danke. Bin über das "host" in der vzlogger.conf gestolpert und hab
deswegen einen per Netzwerk angebundenen Lesekopf erwartet.

**Comment by BoxSo** [comment]
> Vielleicht ein Caching-Problem - gut dass es jetzt klappt! Dann solltest du wie von J-A-U angedeutet vielleicht noch überlegen, ob du nicht die Aggregation im vzlogger nutzen willst, aktuell sammelst du sehr viele Datensätze, die die Speicherkarte stressen und wahrscheinlich nicht in der Auflösung (1-3s) gebraucht werden. Sorry für's OT: Was für einen Lesekopf hast du da im Einsatz? Ist der per WLAN angebunden?
> […](#)

Gegen ein Caching-Problem spricht eigentlich, dass das Problem auf mehreren Clients zu beobachten war (Smartphone, Macbook, Tablet).

Die Aggregation werde ich mir zeitnah ansehen, Danke für den Tipp! 

Und ja genau, das ist ein Lesekopf von Weidmann.

**Comment by andig** [comment]
Wenns so ist bitte Ticket aufmachen einschl. Kanalkonfiguration.

Viele Grüße, 
Andreas

**Comment by andig** [comment]
Geht es denn jetzt? Dann könnten wir hier zumachen...
