### ISSUE TITLE
Frontend Darstellungslücken im Liniendiagramm

### ISSUE THREAD

**Issue by Clautens** [volkszaehler/volkszaehler.org#782]
Hallo zusammen!
ich bekomme im Frontend nicht zusammenhängende Linien zu sehen (Die Beriche zwischen zwei Datenpunkten sind nicht verbunden):
![Screenshot](https://user-images.githubusercontent.com/58749805/70565796-1d10bc80-1b93-11ea-80fe-bc660a6f1a29.png)

Die Bereiche sind manchmal auch größer und obwohl Datenpunkte vorhanden sind, wird die Linie nicht weitergeführt:
![2019-12-10 20_58_41-Window](https://user-images.githubusercontent.com/58749805/70565839-3c0f4e80-1b93-11ea-9fbe-a738d6880ac4.png)

Version: Date:   Mon Nov 25 10:34:37 2019 +0100
Verhalten taucht bei verschiedenen Browsern auf.

Viele Grüße!
Karl

**Comment by frankrichter** [comment]
Schau mal hier:
https://github.com/volkszaehler/volkszaehler.org/blob/4c11705638ce0daeb6c56f3de95d173299ecd9f0/htdocs/js/options.js#L57

**Comment by Clautens** [comment]
passt!
Vielen Dank :-)
