### ISSUE TITLE
Add persistent conf directory to docker-compose.yml

### ISSUE THREAD

**Issue by bgewehr** [volkszaehler/volkszaehler.org#785]
To be able to update the containers from the repository without having to reconfigure all settings, I suggest to have persistent host storage mapped to the containers config folders so that an update will use those and runs with the existing configuration.

If I missed some existing approach to this, please tell.

Any update guideline would be helpful as well, didn‘t find anything on the web.

**Comment by andig** [comment]
There is no need for docker volumes, you can just mount individual (config) files into the container. For howto discussions please use the mailing list.
