### ISSUE TITLE
"Economical" logging of data points, maximum time interval? 

### ISSUE THREAD

**Issue by michis0806** [volkszaehler/volkszaehler.org#794]
Hello, everybody,

I also use volkszaehler to log temperature readings from various sources. Amongst others from zigbee temperature sensors attached to a Deconz gateway and shelly water sensors. 

Both types of devices save power by only sending new values when they have changed (e.g. only every 0.5° change). I have solved the equipping of the interface via iobroker, which reacts to changes in values and then sends them via http-request to the census meter.

My problem now is that I have regular gaps in the frontend, e.g. when there are one or two hours between data points.

Can I intercept this somehow? I have now temporarily switched hard to a 5min interval, but I would like to switch to the change-based solution.

Thanks
Michael

**Comment by jahir** [comment]
htdocs/js/options.js
```
gap: 3600, // chart gap if no tuples for specified number of seconds
```
would be nice to make this configurable in the frontend itself...
