### ISSUE TITLE
Raspberry Pi Image Download is dead

### ISSUE THREAD

**Issue by Bingo2023** [volkszaehler/volkszaehler.org#796]
Hallo,

Ist eigentlich kein richtiges Issue, ich weiss aber nicht wo ich es sonst schreiben kann.

Der Download auf der Hauptseite geht nicht mehr:
https://wiki.volkszaehler.org/howto/raspberry_pi_image
https://demo.volkszaehler.org/downloads/volkszaehler_latest.zip

Kann das einger neu uploaden? Ich mag mir das Image nochmal ziehen.

**Comment by justinotherguy** [comment]
Danke für den Hinweis - das Image ist versehentlich einer übereifrigen Aufräumaktion zum Opfer gefallen - sorry!

Das Image wird so bald als möglich wieder bereit gestellt (vrs. noch heute).

Sorry für die Umstände!

**Comment by justinotherguy** [comment]
@Bingo2023 bitte testen - sollte behoben sein

**Comment by Bingo2023** [comment]
geht, TOP.
vielen Dank für die schnelle Hilfe.

**Comment by AndyO65** [comment]
Hallo volkszaehler.org,
seit ich das Projekt volkszaehler.org gefunden haben, ist das Projekt fast nicht erreichbar. 
Liegt ein Serverproblem vor oder wird die Seite nur extrem heufig aufgerufen?
Grüße
Andreas

**Comment by J-A-U** [comment]
Am Server wird gearbeitet, bitte etwas Geduld.
