### ISSUE TITLE
Error in docker-compose.yml

### ISSUE THREAD

**Issue by DonKracho** [volkszaehler/volkszaehler.org#810]
config.dist.yaml (source of config.yaml) has no entry '127.0.0.1' It uses 'localhost' instead. Therfore the sed commands in docker-compose.yml do fail setting the database.

I tried to use volkszaehler docker on a QNAP with an VZ database already existing in a native mysql database. Because setting the database IP did fail VZ could not connect to the database.

B.T.W great work! Now i can get rid of the Raspberry Pi running in parallel to the NAS. The NAS docker performs faster than the Pi. Because QNAP uses port 8080 for its own Configuration Web-UI I implemented a port forwarding from 8090 to 8080

This this my aprproach of the **docker-compose.yaml** to use a volkszaehhler docker on a ONAP TS-563 with an already existing database and VZ-Users exsisting too:

`version: '3'
services:

  volkszaehler:
    image: volkszaehler/volkszaehler
    ports:
    - 8090:8080
    # NOTE: The init command will only work once the database is fully up and running.
    #       By putting restart: always docker-compose will retry starting this container
    #       and finally complete the database setup sequence.
    command: sh -c "
      sed -i s/localhost/IP4 of your database/ /vz/etc/config.yaml &&
      sleep 1 &&
      /vz/vendor/bin/ppm start -c /vz/etc/middleware.json --static-directory /vz/htdocs --cgi-path=/usr/bin/php"
    networks:
    - volkszaehler
    restart: always

  push-server:
    image: volkszaehler/volkszaehler
    ports:
    - 5582:5582
    - 8082:8082
    command: sh -c "
      sed -i s/localhost/IP4 of your database/ /vz/etc/config.yaml &&
      /vz/bin/push-server"
    networks:
    - volkszaehler
    restart: always

networks:
  volkszaehler:`

**Comment by andig** [comment]
Could I ask you to submit a PR? I'm traveling these days and have little chance to touch the code.

**Comment by DonKracho** [comment]
you are welcome, done.
