### ISSUE TITLE
Data tooltip would be cool

### ISSUE THREAD

**Issue by etas-github-sb** [volkszaehler/volkszaehler.org#838]
Hi all, I am using vz for few months now. I already have quite some data sources and it is getting a bit hard to find the data line that I am interested in.

But there is already this round circle which snaps to the data line near it - pretty cool.

My enhancement idea would be to additionally show the value of the snapped point as tooltip.

So instead of
![image](https://user-images.githubusercontent.com/70331710/103737148-e30e2600-4ff1-11eb-962c-4113e377675d.png)

something like
![image](https://user-images.githubusercontent.com/70331710/103737699-f968b180-4ff2-11eb-940a-7e61691ba7f5.png)

Thanks for your help.

**Comment by r00t-** [comment]
this maybe (an extension to the plotting library used by the frontend):
https://github.com/krzysu/flot.tooltip
(or something similar that is not unmaintained)
