### ISSUE TITLE
network error demo.volkszaehler.org when accessing volkszaehler gui

### ISSUE THREAD

**Issue by oriziena** [volkszaehler/volkszaehler.org#848]
Hi @all,

hopefully this is not a completely dumb issue...

afterupgrading to latest volkszaehler release I am experiencing the issue, that the demo page stuff seems not to be reachable anymore. is there a way to deactivate that ?
<img width="790" alt="Bildschirmfoto 2021-03-21 um 12 12 28" src="https://user-images.githubusercontent.com/2290949/111902671-e3d62600-8a3e-11eb-8b72-3fe5a8d34e8a.png">

How to fix that stuff? thanks
BR
Oriziena

**Comment by J-A-U** [comment]
https://github.com/volkszaehler/volkszaehler.org/blob/c0634e45fddedd8baa4a0c0a2c5248a09cd1489a/htdocs/js/options.js#L49

https://www.photovoltaikforum.com/thread/153815-network-error-error/


mfg JAU

**Comment by oriziena** [comment]
hi,

okay... that was fast, easy and efficient...

therefore closing it ..

thanks @J-A-U
