### ISSUE TITLE
Wiki Performance

### ISSUE THREAD

**Issue by mjaschen** [volkszaehler/volkszaehler.org#851]
Hi there,

I noticed that the wiki pages often timeout (“This site can’t be reachedwiki.volkszaehler.org took too long to respond.”). Is that a known issue?

**Comment by J-A-U** [comment]
Yes, it's known. I expect our admin is still working on the solution (which isn't quite obvious).

**Comment by mjaschen** [comment]
Thanks for the update.

**Comment by J-A-U** [comment]
Someone please close this.
