### ISSUE TITLE
sml - crc check

### ISSUE THREAD

**Issue by isarrider** [volkszaehler/volkszaehler.org#858]
Hi,

I sometimes get weird results,
I think maybe some bits are flipped on my SML meter...
Is there any was to see if the crc check of the SML frame is valid?
Is it reported to the vzlogger.log?

Thx...

**Comment by J-A-U** [comment]
Messages with improper CRC are discarded. With mention in the log.

mfg JAU

**Comment by andig** [comment]
Sounds like related to vzlogger.
