### ISSUE TITLE
"network error" 

### ISSUE THREAD

**Issue by white-rabbit07** [volkszaehler/volkszaehler.org#862]
Hi. 
Recently I get this message whenever I open the GUI:
![Screenshot_20210609_171647](https://user-images.githubusercontent.com/17621425/121382436-e44bd200-c946-11eb-8e70-aa45171e2d96.png)
What's wrong? A reboot didn't fix it :)

**Comment by J-A-U** [comment]
When everything else is still working its only the demoserver (today not available).
You can remove it from your configuration:
https://github.com/volkszaehler/volkszaehler.org/blob/master/htdocs/js/options.js#L50
