### ISSUE TITLE
Problem beim Middleware Frontend

### ISSUE THREAD

**Issue by Moddy21** [volkszaehler/volkszaehler.org#869]
Leider kann ich im Frontend weiterhin keine Kanäle konfigurieren. Hat irgendwer eine Idee? Wo das Problem liegt. Wenn wir auf speichern klicken um einen Kanal anzulegen passiert nix. Er ist dann auch weder unter Privat oder Öffentlich aufrufbar, fast so als ob es nicht speichert. Der Fehler erscheint nach dem Versuch einen Kanal aus der Demo zu bearbeiten. Gibt es irgendwelche Logs wo man Details prüfe…

**Comment by andig** [comment]
Bitte auf der Mailingliste fragen.
