### ISSUE TITLE
Watchdog for vzlogger

### ISSUE THREAD

**Issue by ragflyer** [volkszaehler/volkszaehler.org#873]
Hi,
is there a good way to monitor health of the vzlogger process?
Ocasionally it hangs at high cpu load which I catch with a cronjob and restart it, but now it also seems to hang and not forward data to influxdb after a couple of days.
I would really like to help debugging but the logs did not give any clues, and a workaround for the moment would be nice.
Kind regards

**Comment by r00t-** [comment]
i think implementing a "watchdog" feature inside vzligger would be more work than finding and fixing the actual bug.
also, such a wstchdog should exist outside of vzlogger for maximum reluability.
for example a script that checks if your database is receiving new data, and restart vzlogger if not.

as for debugging:
- do you have the loglevel set to the maximum?
- when vzlogger is broken, run `strace -p` on it and log some output, so we can see if it's stuck retrying some failing i/o (and which) or internally spinning.
- maybe `kill -SEGV` vzlogger (end ensure coredumps are enabled, aka `ulimit -c 0` before starting it) to create a corefile (make sure you have an unstripped binary with debug info - this is the default iirc, `file` can tell you.)
- if you have multiple meters, maybe split your config to monitor them in separate vzlogger instances, to find if a specific meter is causing the issue.

**Comment by r00t-** [comment]
alao, a vzlofger issue should be logged at https://github.com/volkszaehler/vzlogger/issues , not here.

**Comment by ragflyer** [comment]
OK thanks, will collect some more data and log an issue at the correct place. For anyone looking for a simple way to restart the process , I have a cronjob running this script to check if cpu load by vzlogger is high (had this at 98, didn't catch all freezes, then at 60, still didn't catch all, not at 11% it seems catch all cases):

crontab -e
then insert:
`*/5 * * * * /root/vzrestart.sh`

create executable /root/vzrestart.sh, then insert:
`count=$( ps -C vzlogger -o pid=,pcpu= |awk -F " " '$2>11 {print $2}' )

if [ $count ];
then
	echo "restarting vzlogger now"
	date >> /root/vzrestart.txt
	systemctl restart vzlogger
else
	echo "still ok"
fi
`

**Comment by andig** [comment]
Closing- this is not the vzlogger repo and not the mailing list
