### ISSUE TITLE
PHP Fatal error during installation of Middleware

### ISSUE THREAD

**Issue by olischuch** [volkszaehler/volkszaehler.org#874]
Hello all,

Im facing some strange issues during the installation of the middleware.

I have followed these instructions so far and they went quite smooth:

https://wiki.volkszaehler.org/software/controller/vzlogger/installation_cpp-version

after settings up the vzlogger my plan was to configure the middleware via this instruction.

https://wiki.volkszaehler.org/software/middleware/installation

already at the package for php I got this message

`Package php-opcache is a virtual package provided by:
  php7.3-opcache 7.3.29-1~deb10u1
  php7.2-opcache 7.2.9-1+b2
  php7.1-opcache 7.1.20-1+b2
You should explicitly select one to install.`

and went with `php7.3-opcache` ahead.

When performing `bash install.sh` I get this error:

`create volkszaehler.org database and admin user? [y]
creating database volk1...
creating db user vz-admin...
creating database schema...
~/volkszaehler.org ~
PHP Fatal error:  Uncaught Error: Class 'Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper' not found in /home/pi/volkszaehler.org/bin/doctrine:34
Stack trace:
#0 {main}
  thrown in /home/pi/volkszaehler.org/bin/doctrine on line 34`

I already tried it several times with other php versions or a manual installation of doctrine `sudo apt-get install -y php-doctrine-dbal`

but nothing helped.

did I miss something? I would be happy if somebody could help me here.

Thanks.

Edit: Is this the right place for such kind of questions?

**Comment by adlerweb** [comment]
The script probably thinks you've already installed the controller. You might want to consider a manual installation, there it is easier to spot problems.

To fix the current error:
- cd into vz directory
- if composer.phar does not exist: `php -r "eval('?>'.file_get_contents('https://getcomposer.org/installer'));"` *
- if composer.lock does not exist: `./composer.phar install --no-dev`
- otherwise: `./composer.phar update`

**Comment by adlerweb** [comment]
No, volkszaehler itself (aka middleware). If you haven't specified otherwise the script uses ~/volkszaehler.org

**Comment by olischuch** [comment]
any chance to install an older or the correct doctrine version?

**Comment by schnello** [comment]
@andig 
Would a PR with the change from "doctrine/dbal": "^2.12|^3.0" to "doctrine/dbal": "^2.13.3" from your view be OK?

**Comment by jahir** [comment]
> @andig Would a PR with the change from "doctrine/dbal": "^2.12|^3.0" to "doctrine/dbal": "^2.13.3" from your view be OK?

Why 2.13.3? VZ works with ^2.12, so I guess we should stick with that.

**Comment by andig** [comment]
In https://github.com/volkszaehler/volkszaehler.org/commit/b24cd2fddb8913f022d31b9d6b15c5d3c3abc10e geändert
