### ISSUE TITLE
What is needed to run the backend with postgresql?

### ISSUE THREAD

**Issue by narc-Ontakac2** [volkszaehler/volkszaehler.org#885]
Once upon a time the backend worked with postgresql. I would like to run the backend on postgresql with timescaledb and grafana, simply because I prefer postgresqls more suitable sql dialect. A short writeup of how this could possibly done would be helpful.

Thx.

**Comment by andig** [comment]
Afaik it still works with postgresql.

**Comment by maazl** [comment]
I am running the recent version of volkszaehler on a PostgreSQL 17.9. I had to do only two source code patches so far: the SQL in function sqlCount and dbSize.
I did not use aggregations so far. But this would likely not require major changes too.
