### ISSUE TITLE
Deprecated:  Return type of Volkszaehler\Interpreter\Interpreter::getIterator()

### ISSUE THREAD

**Issue by andig** [volkszaehler/volkszaehler.org#897]
PHP 8.1:

Deprecated:  Return type of Volkszaehler\Interpreter\Interpreter::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/andig/htdocs/vz/lib/Interpreter/Interpreter.php on line 151

**Comment by jahir** [comment]
fixed via #905
