### ISSUE TITLE
composer.lock is not checked in - dependency symfony 6.1 seems broken

### ISSUE THREAD

**Issue by wrichter** [volkszaehler/volkszaehler.org#907]
I have problems rebuilding the docker container (for ARM). The container builds, but a newer version of symfony (6.1) is being pulled in which doesn't work properly. Could you please check in your composer.lock (it is in .gitignore) file so I know which version you're using?

https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control

**Comment by andig** [comment]
Symfony 6 should not be pulled because that major version is not in the composer.json. If that happens it seems like a composer bug.

**Comment by andig** [comment]
> which doesn't work properly.

What happens exactly?

**Comment by wrichter** [comment]
https://gist.github.com/wrichter/eb8fa98d50c87ef82898cf6f13b7f6dd

**Comment by wrichter** [comment]
In Process.php line 311:

  syntax error, unexpected token ")"

**Comment by andig** [comment]
Can you repro without podman? I'm not hitting this locally with php 8.1

**Comment by andig** [comment]
And what is `Process.php`?

**Comment by wrichter** [comment]
> Can you repro without podman? I'm not hitting this locally with php 8.1. I'm seeing another error with `preg_match` though...

Podman is an alternative to docker. I don't have a local build env, I am using containers only. The problem occurs at run time, not at build time.

> And what is `Process.php`?

Some component in symfony I suppose

**Comment by andig** [comment]
Siehe https://github.com/volkszaehler/volkszaehler.org/pull/913#issuecomment-1202420158- kannst Du das mit Apache reproduzieren oder betrifft das nur PPM?

**Comment by andig** [comment]
Was mich verwirrt ist, dass hier eine `symfony/process` Version installiert wird, die mit Deinem PHP nicht ausführbar ist. Das dürfte bei sauberen Version Constraints der notwendigen PHP Version eigentlich nicht passieren. Was sagt

    composer why symfony/process

und welche PHP Version hast Du?

**Comment by andig** [comment]
@wrichter sollen wir die Diskussion in #913 zusammen führen?

**Comment by wrichter** [comment]
Ja gerne - dann können wir das hier schliessen
