### ISSUE TITLE
Frage zu ehz vzlooger Ausgabe von Leistungswerten mit/ohne Vorzeichen

### ISSUE THREAD

**Issue by michis0806** [volkszaehler/volkszaehler.org#911]
Hi zusammen,

erstmal sorry, dass ich das Board hier für eine allgemein Frage missbrauche. Aber ich hab sonst keinen Anhaltspunkt, wie ich den Fehler in den Griff bekommen soll...

Ich hab hier in zwei Häusern den vzlogger mit selbstgebauten IR-Köpfen am laufen. Beide Häuser haben einen Zweiwege-Zähler und einen Erzeugungs-Zähler. Beide Zähler sind (augenscheinlich) die gleichen.

In Haus 1 funktioniert alles wunderbar. Ich bekomme am Zweiwegezähler die beiden Zählerstände und die aktuelle Leistung mit Vorzeichen (!) also + für Bezug und - für Einspeisung.

In Haus 2 funktioniert alles bis eben auf die aktuelle Leistung. Hier bekomme ich nur den absoluten Wert ohne Vorzeichen. Ich hab schon die beiden RasPis getauscht, das unterschiedliche Verhalten bleibt aber bestehen.

Kennt jemand den "Fehler"? Gibt's ne Möglichkeit irgendwie den Zähler dazu zu bewegen, auch die Vorzeichen zu liefern? 

Ach ja, beide Zähler stammen vom gleichen Netzbetreiber. Sind allerdings rund 4 Jahre dazwischen. Haus 1 stammt von 2016 der Zähler von Haus 2 von 2012...

Danke vielmals ;)

Michael

PS: Falls jemand ein Forum o.ä. kennt, das solche Fragen evtl. auch beantworten kann, ich bin für jeden Tipp dankbar...

**Comment by andig** [comment]
Die Frage gehört auf die Mailingliste- da lesen die Zählerexperten mit ;)
