### ISSUE TITLE
Where to find JSON Schema for clients

### ISSUE THREAD

**Issue by Fab1n** [volkszaehler/volkszaehler.org#912]
I'd like to write a small client for VZ to display data. For that I need to access the data via the JSON API. Is there any documentation for paths and parameters and which entities to expect as return values?

Do I need to read the VZ sources in order to find out?

**Comment by jahir** [comment]
[API reference](https://wiki.volkszaehler.org/development/api/reference)

**Comment by andig** [comment]
Happy to take a pr ;)
