### ISSUE TITLE
Add/activate Docker integration test

### ISSUE THREAD

**Issue by jahir** [volkszaehler/volkszaehler.org#916]
Wie in #915 bemerkt, laufen aktuell keine Docker-Integrationstests.

@StefanSchoof kannst du das machen oder kurz erläutern, was man dafür machen müßte?

**Comment by J-A-U** [comment]
Soweit ich mich erinnere haben wir den mit Absicht weg gelassen um die Rechnerzeit auf Github nicht unnötig aufzublähen. Kostet uns zwar nix, aber das könnte sich ändern wenn wir mit der Resourcen nicht bedacht umgehen.
Siehe dazu die letzten Diskussionen um Tests/Travis/etc.

**Comment by StefanSchoof** [comment]
Ich würde vorschlagen als erstes ein einfache Pipeline bauen die das docker image baut und einmal kurz testet, ob es anfragen annimmt. Ich würde das als zusätzlichen build workflow sehen. Dann lässt sich einfacher sehen, ob das ein docker oder andere Fehler ist. Ich könnte einen einfachen Vorschlag erstellen.

Die Frage ist, ob man das nur für den default branch macht oder auch schon für PRs und/oder zeitlich wiederholend. Docker hat auf github einen ganz guten Cache der nach meiner Erfahrung viele builds deutlich abkürzt. Aber es benötigt ohne Frage Ressourcen auf dem github agents. Wenn es aber Fehler findet, spart es menschliche Ressourcen.

Geht es hier nur um einen docker integration test oder auch um das aktualisieren des images auf docker hub und/oder github container registry?

**Comment by jahir** [comment]
> Ich würde vorschlagen als erstes ein einfache Pipeline bauen die das docker image baut und einmal kurz testet, ob es anfragen annimmt. Ich würde das als zusätzlichen build workflow sehen. Dann lässt sich einfacher sehen, ob das ein docker oder andere Fehler ist. Ich könnte einen einfachen Vorschlag erstellen.

Genau sowas hatte ich mir vorgestellt. Wäre super, wenn du das machen könntest.

> Die Frage ist, ob man das nur für den default branch macht oder auch schon für PRs und/oder zeitlich wiederholend.

Wenn die Rechenzeit in der Vergangenheit ein Problem war, müssen wir wohl schon etwas aufpassen, könnten aber aber im Problemfall ja auch zurückgedreht werden.
Bei PRs wäre m.E. der größte Nutzen (und so viele haben wir i.A. ja auch nicht).

Das Image bei Docker Hub wäre schon schön, das Image dort ist ja schon zwei Jahre alt. @andig, du hast das zuletzt aktualisiert, was meinst du dazu?

**Comment by andig** [comment]
Rechenzeit ist bei GH kein Problem mehr, build-on-commit auf master sollte völlig genügen. Im Moment liegt das Image in einer Docker Org- dafür bräuchten wir einen Maintainer der das mit mehr Elan als ich voran treiben könnte, gerne auch für die Automatisierung des Repos hier. Den Travis Umzug hab ich ja schon nicht mehr voll umgesetzt.... Findet sich da jemand?

**Comment by StefanSchoof** [comment]
Ich kann mir vorstellen für die docker images ein paar PR zu machen und ein Auge drauf zu haben. Ich bräuchte, aber Leute die kritische auf die PRs schauen und mitdenken, in welche Richtung das gehen soll. 

@andig Was meinst du mit "Automatisierung des Repos"?
