### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Pferdebockwurst** [volkszaehler/volkszaehler.org#921]
Excuse me, this might be the wrong place to ask, but I don't know a better one!

Is the website volkszaehler.org down?

**Comment by justinotherguy** [comment]
you're alright :)
yes, the site is currently down - we're working on bringing it back

**Comment by Pferdebockwurst** [comment]
Thanks!

**Comment by justinotherguy** [comment]
Running again; thanks for the report! :)
