### ISSUE TITLE
403 error in apache2 nach genauer anleitung des volkszähler

### ISSUE THREAD

**Issue by yukimaotec** [volkszaehler/volkszaehler.org#927]
hallo ich ahbe versuch den volkszähler auf einen x86_64 ubuntu 20.04.6 lts zu installieren und habe dafür die anleitung auf volkszähler.org verwendet doch ohne erfolg. ich habe das problem das ich immer egal was ich tue den fehler 403 forbidden bekomme.

[Wed Mar 22 05:04:43.221762 2023] [mpm_event:notice] [pid 9625:tid 139829250726976] AH00489: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 22 05:04:43.222276 2023] [core:notice] [pid 9625:tid 139829250726976] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 22 05:20:54.281545 2023] [mpm_event:notice] [pid 9625:tid 139829250726976] AH00491: caught SIGTERM, shutting down
[Wed Mar 22 05:20:54.438000 2023] [mpm_event:notice] [pid 12376:tid 140257344986176] AH00489: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 22 05:20:54.438232 2023] [core:notice] [pid 12376:tid 140257344986176] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 22 05:20:57.690438 2023] [core:error] [pid 12377:tid 140257215358720] [client 192.168.188.53:56663] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:22:00.667953 2023] [core:error] [pid 12378:tid 140257215358720] [client 192.168.188.53:56665] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:24:01.837578 2023] [core:error] [pid 12377:tid 140257165002496] [client 192.168.188.53:56675] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:24:01.883774 2023] [core:error] [pid 12377:tid 140257198573312] [client 192.168.188.53:56675] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org, referer: http://192.168.188.164/
[Wed Mar 22 05:29:37.557765 2023] [core:error] [pid 12378:tid 140257198573312] [client 192.168.188.53:56714] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:29:37.604893 2023] [core:error] [pid 12378:tid 140257190180608] [client 192.168.188.53:56714] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org, referer: http://192.168.188.164/
[Wed Mar 22 05:31:35.494255 2023] [core:error] [pid 12378:tid 140257173395200] [client 192.168.188.53:56717] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:31:35.552483 2023] [core:error] [pid 12378:tid 140257232144128] [client 192.168.188.53:56717] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org, referer: http://192.168.188.164/
[Wed Mar 22 05:32:26.866586 2023] [core:error] [pid 12377:tid 140257190180608] [client 192.168.188.53:56718] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:32:26.910274 2023] [core:error] [pid 12377:tid 140257232144128] [client 192.168.188.53:56718] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org, referer: http://192.168.188.164/
[Wed Mar 22 05:32:28.091664 2023] [core:error] [pid 12377:tid 140257156609792] [client 192.168.188.53:56719] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:32:28.131504 2023] [core:error] [pid 12377:tid 140257148217088] [client 192.168.188.53:56719] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org, referer: http://192.168.188.164/
[Wed Mar 22 05:32:28.272905 2023] [core:error] [pid 12377:tid 140257131431680] [client 192.168.188.53:56720] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:32:28.448188 2023] [core:error] [pid 12377:tid 140257173395200] [client 192.168.188.53:56720] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:32:28.633577 2023] [core:error] [pid 12377:tid 140257181787904] [client 192.168.188.53:56720] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:32:28.816420 2023] [core:error] [pid 12377:tid 140257114646272] [client 192.168.188.53:56720] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:32:28.990258 2023] [core:error] [pid 12377:tid 140257072682752] [client 192.168.188.53:56720] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:32:39.015459 2023] [core:error] [pid 12377:tid 140257097860864] [client 192.168.188.53:56721] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:33:31.264324 2023] [mpm_event:notice] [pid 12376:tid 140257344986176] AH00491: caught SIGTERM, shutting down
[Wed Mar 22 05:34:23.315509 2023] [mpm_event:notice] [pid 807:tid 140131824970816] AH00489: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 22 05:34:23.321812 2023] [core:notice] [pid 807:tid 140131824970816] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 22 05:34:27.276860 2023] [core:error] [pid 811:tid 140131688244992] [client 192.168.188.53:56726] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:34:27.320652 2023] [core:error] [pid 811:tid 140131679852288] [client 192.168.188.53:56726] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org, referer: http://192.168.188.164/midd>
[Wed Mar 22 05:34:34.003807 2023] [core:error] [pid 811:tid 140131663066880] [client 192.168.188.53:56727] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:34:34.050021 2023] [core:error] [pid 811:tid 140131654674176] [client 192.168.188.53:56727] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org, referer: http://192.168.188.164/
[Wed Mar 22 05:44:58.137950 2023] [core:error] [pid 811:tid 140131646281472] [client 192.168.188.53:56756] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:44:58.185538 2023] [core:error] [pid 811:tid 140131621103360] [client 192.168.188.53:56756] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org, referer: http://192.168.188.164/
[Wed Mar 22 05:44:59.437747 2023] [core:error] [pid 811:tid 140131545569024] [client 192.168.188.53:56757] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:44:59.477392 2023] [core:error] [pid 811:tid 140131604317952] [client 192.168.188.53:56757] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org, referer: http://192.168.188.164/
[Wed Mar 22 05:44:59.657488 2023] [core:error] [pid 811:tid 140131595925248] [client 192.168.188.53:56758] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:44:59.850190 2023] [core:error] [pid 811:tid 140131587532544] [client 192.168.188.53:56758] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:45:00.043039 2023] [core:error] [pid 811:tid 140131579139840] [client 192.168.188.53:56758] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:45:00.250404 2023] [core:error] [pid 811:tid 140131570747136] [client 192.168.188.53:56758] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:45:00.433492 2023] [core:error] [pid 811:tid 140131813951232] [client 192.168.188.53:56758] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:47:28.570362 2023] [mpm_event:notice] [pid 807:tid 140131824970816] AH00491: caught SIGTERM, shutting down
[Wed Mar 22 05:47:28.722681 2023] [mpm_event:notice] [pid 1456:tid 140130277739584] AH00489: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 22 05:47:28.722942 2023] [core:notice] [pid 1456:tid 140130277739584] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 22 05:47:31.246717 2023] [core:error] [pid 1458:tid 140130266720000] [client 192.168.188.53:56760] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:47:32.853258 2023] [core:error] [pid 1458:tid 140130258327296] [client 192.168.188.53:56760] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:47:32.888628 2023] [core:error] [pid 1458:tid 140130249934592] [client 192.168.188.53:56760] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org, referer: http://192.168.188.164/
[Wed Mar 22 05:47:33.044425 2023] [core:error] [pid 1458:tid 140130233149184] [client 192.168.188.53:56761] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:47:33.233931 2023] [core:error] [pid 1458:tid 140130018916096] [client 192.168.188.53:56761] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:47:33.428749 2023] [core:error] [pid 1458:tid 140130010523392] [client 192.168.188.53:56761] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:47:33.620008 2023] [core:error] [pid 1458:tid 140130002130688] [client 192.168.188.53:56761] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:47:33.809980 2023] [core:error] [pid 1458:tid 140130102777600] [client 192.168.188.53:56761] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:48:18.567391 2023] [mpm_event:notice] [pid 1456:tid 140130277739584] AH00491: caught SIGTERM, shutting down
[Wed Mar 22 05:48:18.708613 2023] [mpm_event:notice] [pid 1550:tid 140328873544768] AH00489: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 22 05:48:18.708846 2023] [core:notice] [pid 1550:tid 140328873544768] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 22 05:48:21.593009 2023] [core:error] [pid 1551:tid 140328711444224] [client 192.168.188.53:56762] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org
[Wed Mar 22 05:48:41.574221 2023] [mpm_event:notice] [pid 1550:tid 140328873544768] AH00491: caught SIGTERM, shutting down
[Wed Mar 22 05:48:41.744646 2023] [mpm_prefork:notice] [pid 3282] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 22 05:48:41.744902 2023] [core:notice] [pid 3282] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 22 05:48:43.122060 2023] [mpm_prefork:notice] [pid 3282] AH00169: caught SIGTERM, shutting down
[Wed Mar 22 05:48:43.537000 2023] [mpm_prefork:notice] [pid 3378] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations

**Comment by J-A-U** [comment]
Hallo yukimaotec,

im Wiki sind mehrere Lösungen beschreiben, welche hast du gewählt?

Die Fehlermeldung deutet meiner Ansicht nach darauf hin das dein Document Root falsch gesetzt ist.
Der Ordner /var/www/volkszaehler.org ist aus gutem Grund nicht für Zugriffe von Außen freigegeben.
Der öffentliche Teil liegt unter /var/www/volkszaehler.org/htdocs.

Grüße
Daniel Lauckner

***@***.*** schrieb am Freitag, 24. März 2023 um 14:25 Uhr:
> hallo ich ahbe versuch den volkszähler auf einen x86_64 ubuntu 20.04.6 lts zu installieren und habe dafür die anleitung auf volkszähler.org verwendet doch ohne erfolg. ich habe das problem das ich immer egal was ich tue den fehler 403 forbidden bekomme.

> [Wed Mar 22 05:04:43.221762 2023] [mpm_event:notice] [pid 9625:tid 139829250726976] AH00489: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
> [Wed Mar 22 05:04:43.222276 2023] [core:notice] [pid 9625:tid 139829250726976] AH00094: Command line: '/usr/sbin/apache2'
> [Wed Mar 22 05:20:54.281545 2023] [mpm_event:notice] [pid 9625:tid 139829250726976] AH00491: caught SIGTERM, shutting down
> [Wed Mar 22 05:20:54.438000 2023] [mpm_event:notice] [pid 12376:tid 140257344986176] AH00489: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
> [Wed Mar 22 05:20:54.438232 2023] [core:notice] [pid 12376:tid 140257344986176] AH00094: Command line: '/usr/sbin/apache2'
> [Wed Mar 22 05:20:57.690438 2023] [core:error] [pid 12377:tid 140257215358720] [client 192.168.188.53:56663] AH00037: Symbolic link not allowed or link target not accessible: /var/www/volkszaehler.org

**Comment by yukimaotec** [comment]
hallo ich habe die anleitung unter https://wiki.volkszaehler.org/software/middleware/installation genutzt, undzwar PPM als Server
und Apache als Proxy
ich kann gerne mehr infos geben nur denke ich wen man eine anleitung befolgt sollte man zu ein funktionierenten ergenis kommen  
danke

**Comment by J-A-U** [comment]
Hallo yukimaotec,

zeige mal bitte deine /etc/apache2/apache2.conf

Grüße
Daniel Lauckner

***@***.*** schrieb am Freitag, 24. März 2023 um 14:49 Uhr:
> hallo ich habe die anleitung unter https://wiki.volkszaehler.org/software/middleware/installation genutzt, undzwar PPM als Server
> und Apache als Proxy
> ich kann gerne mehr infos geben nur denke ich wen man eine anleitung befolgt sollte man zu ein funktionierenten ergenis kommen  
> danke

**Comment by J-A-U** [comment]
/etc/apache2/sites-enabled/000-default.conf ?

**Comment by J-A-U** [comment]
`ls -l /var/www/volkszaehler.org` ?

**Comment by yukimaotec** [comment]
lrwxrwxrwx 1 root root 22 Mär 24 14:49 /var/www/volkszaehler.org -> /root/volkszaehler.org

**Comment by J-A-U** [comment]
Homedir von root als Installationsort scheint mir keine sichere Lösung.

`ls -al /root | grep volks` ?

**Comment by yukimaotec** [comment]
der server wird vom internet genommen sobalt der leuft

**Comment by J-A-U** [comment]
Das hat mit Internet nix zu tun.

Ich würde mal sagen du hast dich da selbst in die Ecke manövriert. Der User unter dem Apache läuft hat eher beschränkte Zugangsrechte.

**Comment by yukimaotec** [comment]
ok wie kann ich das fixen

**Comment by yukimaotec** [comment]
zudem wie soll ich das gentan haben ich habe ledigtlich die anleitung befolgt

**Comment by J-A-U** [comment]
Man arbeitet nicht als root am Rechner. Linux-Grundlage, Standardverfahren, Best Practice. Sowas muss man eigentlich nicht mehr erklären. Bzw. es ist bei den meisten Distributionen üblich das man sich als root gar nicht mehr anmelden kann.

Erstelle einen normalen User. Installiere VZ, als dieser User, in dessen Homedir. Ev. musst du den User in die Gruppe www-data mit aufnehmen.

**Comment by yukimaotec** [comment]
so hab gestern noch den server noch mal ne aufgesetzt und den dienst als user installiert und hab drotzdem kein zugan der fehler besteht immernoch

**Comment by J-A-U** [comment]
Und die Lösung war?

**Comment by yukimaotec** [comment]
Klassiker hattes recht mit root installiert
________________________________
