### ISSUE TITLE
Mailing list mails should contain link to archive

### ISSUE THREAD

**Issue by andig** [volkszaehler/volkszaehler.org#96]
Gibts die Möglichkeit das in der Listenadministration einzustellen (also analog zu den Mails von GitHub)? Dann wäre es deutlich einfacher GitHub requests mit der ML zu verbinden?

**Comment by r00t-** [comment]
persoenlich loese ich das problem (fuer -users) indem ich die liste ohnehin nur im mailman-archiv lese.
der mailto-link (neben dem absendernamen) enthaelt eine thread-referenz, die zB von claws-mail uebernommen wird.
